apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      argocd.argoproj.io/tracking-id: claude-webui:/Service:claude-webui/claude-webui
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"claude-webui:/Service:claude-webui/claude-webui"},"labels":{"app.kubernetes.io/instance":"claude-webui","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"claude-webui","app.kubernetes.io/version":"1.0.0","helm.sh/chart":"claude-webui-1.0.0"},"name":"claude-webui","namespace":"claude-webui"},"spec":{"ports":[{"port":80,"protocol":"TCP","targetPort":3000}],"selector":{"app":"claude-webui","app.kubernetes.io/instance":"claude-webui","app.kubernetes.io/name":"claude-webui"},"type":"ClusterIP"}}
    creationTimestamp: "2026-01-20T06:57:53Z"
    labels:
      app.kubernetes.io/instance: claude-webui
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: claude-webui
      app.kubernetes.io/version: 1.0.0
      helm.sh/chart: claude-webui-1.0.0
    name: claude-webui
    namespace: claude-webui
    resourceVersion: "10147"
    uid: 73e9f384-4fa5-4aa8-a0b8-5af71ccfad21
  spec:
    clusterIP: 10.43.154.222
    clusterIPs:
    - 10.43.154.222
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
    selector:
      app: claude-webui
      app.kubernetes.io/instance: claude-webui
      app.kubernetes.io/name: claude-webui
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
