apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      argocd.argoproj.io/tracking-id: odoo:/Service:odoo/odoo
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"odoo:/Service:odoo/odoo"},"labels":{"app":"odoo"},"name":"odoo","namespace":"odoo"},"spec":{"ports":[{"name":"http","port":8069,"targetPort":8069}],"selector":{"app":"odoo"},"type":"ClusterIP"}}
    creationTimestamp: "2026-01-24T23:36:05Z"
    labels:
      app: odoo
    name: odoo
    namespace: odoo
    resourceVersion: "10281"
    uid: 76800377-4db5-4f4c-bfbf-273b447778b1
  spec:
    clusterIP: 10.43.25.163
    clusterIPs:
    - 10.43.25.163
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http
      port: 8069
      protocol: TCP
      targetPort: 8069
    selector:
      app: odoo
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      argocd.argoproj.io/tracking-id: odoo:/Service:odoo/odoo-db
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"odoo:/Service:odoo/odoo-db"},"labels":{"app":"odoo-postgres"},"name":"odoo-db","namespace":"odoo"},"spec":{"ports":[{"name":"postgres","port":5432,"targetPort":5432}],"selector":{"app":"odoo-postgres"},"type":"ClusterIP"}}
    creationTimestamp: "2026-01-24T23:36:05Z"
    labels:
      app: odoo-postgres
    name: odoo-db
    namespace: odoo
    resourceVersion: "10282"
    uid: 6d344051-1ba1-4f41-bfe1-c9e6b39fd8bb
  spec:
    clusterIP: 10.43.152.47
    clusterIPs:
    - 10.43.152.47
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
    selector:
      app: odoo-postgres
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      argocd.argoproj.io/tracking-id: odoo:/Service:odoo/odoo-nodeport
      gethomepage.dev/description: ERP & CRM
      gethomepage.dev/enabled: "true"
      gethomepage.dev/group: Applications
      gethomepage.dev/href: https://odoo.holm.chat
      gethomepage.dev/icon: odoo.svg
      gethomepage.dev/name: Odoo
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"odoo:/Service:odoo/odoo-nodeport","gethomepage.dev/description":"ERP \u0026 CRM","gethomepage.dev/enabled":"true","gethomepage.dev/group":"Applications","gethomepage.dev/href":"https://odoo.holm.chat","gethomepage.dev/icon":"odoo.svg","gethomepage.dev/name":"Odoo"},"labels":{"app":"odoo"},"name":"odoo-nodeport","namespace":"odoo"},"spec":{"ports":[{"name":"http","nodePort":30069,"port":8069,"targetPort":8069}],"selector":{"app":"odoo"},"type":"NodePort"}}
    creationTimestamp: "2026-01-24T23:36:05Z"
    labels:
      app: odoo
    name: odoo-nodeport
    namespace: odoo
    resourceVersion: "10283"
    uid: 54c679e2-3280-41f4-b289-cd1a389b6d17
  spec:
    clusterIP: 10.43.140.53
    clusterIPs:
    - 10.43.140.53
    externalTrafficPolicy: Cluster
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http
      nodePort: 30069
      port: 8069
      protocol: TCP
      targetPort: 8069
    selector:
      app: odoo
    sessionAffinity: None
    type: NodePort
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
