apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      argocd.argoproj.io/tracking-id: tiktok-archive:/Service:tiktok-archive/tiktok-archive
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"tiktok-archive:/Service:tiktok-archive/tiktok-archive"},"name":"tiktok-archive","namespace":"tiktok-archive"},"spec":{"ports":[{"nodePort":30888,"port":80,"targetPort":80}],"selector":{"app":"tiktok-archive","component":"frontend"},"type":"NodePort"}}
    creationTimestamp: "2026-01-25T20:58:00Z"
    name: tiktok-archive
    namespace: tiktok-archive
    resourceVersion: "10300"
    uid: 6b54dcdd-ebb7-40da-92e8-6439717fbbcd
  spec:
    clusterIP: 10.43.11.59
    clusterIPs:
    - 10.43.11.59
    externalTrafficPolicy: Cluster
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - nodePort: 30888
      port: 80
      protocol: TCP
      targetPort: 80
    selector:
      app: tiktok-archive
      component: frontend
    sessionAffinity: None
    type: NodePort
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      argocd.argoproj.io/tracking-id: tiktok-archive:/Service:tiktok-archive/tiktok-archive-backend
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"tiktok-archive:/Service:tiktok-archive/tiktok-archive-backend"},"name":"tiktok-archive-backend","namespace":"tiktok-archive"},"spec":{"ports":[{"port":8000,"targetPort":8000}],"selector":{"app":"tiktok-archive","component":"backend"}}}
    creationTimestamp: "2026-01-25T20:58:00Z"
    name: tiktok-archive-backend
    namespace: tiktok-archive
    resourceVersion: "10301"
    uid: bd8e724c-a9f4-4571-9d45-71c0509097b2
  spec:
    clusterIP: 10.43.220.185
    clusterIPs:
    - 10.43.220.185
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000
    selector:
      app: tiktok-archive
      component: backend
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      argocd.argoproj.io/tracking-id: tiktok-archive:/Service:tiktok-archive/tiktok-archive-frontend
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"tiktok-archive:/Service:tiktok-archive/tiktok-archive-frontend"},"name":"tiktok-archive-frontend","namespace":"tiktok-archive"},"spec":{"ports":[{"port":80,"targetPort":80}],"selector":{"app":"tiktok-archive","component":"frontend"}}}
    creationTimestamp: "2026-01-25T20:58:00Z"
    name: tiktok-archive-frontend
    namespace: tiktok-archive
    resourceVersion: "10302"
    uid: 95ef54bc-6280-4534-a4ef-06b8252012d0
  spec:
    clusterIP: 10.43.152.154
    clusterIPs:
    - 10.43.152.154
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 80
      protocol: TCP
      targetPort: 80
    selector:
      app: tiktok-archive
      component: frontend
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
