apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      argocd.argoproj.io/tracking-id: homepage:/Service:homepage/homepage
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"homepage:/Service:homepage/homepage"},"labels":{"app.kubernetes.io/instance":"homepage","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"homepage","app.kubernetes.io/service":"homepage","app.kubernetes.io/version":"v1.2.0","helm.sh/chart":"homepage-2.1.0"},"name":"homepage","namespace":"homepage"},"spec":{"ports":[{"name":"http","port":3000,"protocol":"TCP","targetPort":"http"}],"selector":{"app.kubernetes.io/instance":"homepage","app.kubernetes.io/name":"homepage"},"type":"ClusterIP"}}
    creationTimestamp: "2026-01-20T02:17:51Z"
    labels:
      app.kubernetes.io/instance: homepage
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: homepage
      app.kubernetes.io/service: homepage
      app.kubernetes.io/version: v1.2.0
      helm.sh/chart: homepage-2.1.0
    name: homepage
    namespace: homepage
    resourceVersion: "10233"
    uid: a1bc3523-1d9a-42dd-bce1-29a2f6debdd0
  spec:
    clusterIP: 10.43.230.170
    clusterIPs:
    - 10.43.230.170
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http
      port: 3000
      protocol: TCP
      targetPort: http
    selector:
      app.kubernetes.io/instance: homepage
      app.kubernetes.io/name: homepage
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
