apiVersion: v1
kind: Service
metadata:
  name: tiktok-archive-backend
  namespace: tiktok-archive
spec:
  selector:
    app: tiktok-archive
    component: backend
  ports:
    - port: 8000
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: tiktok-archive-frontend
  namespace: tiktok-archive
spec:
  selector:
    app: tiktok-archive
    component: frontend
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: tiktok-archive
  namespace: tiktok-archive
spec:
  type: NodePort
  selector:
    app: tiktok-archive
    component: frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30888
