apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      argocd.argoproj.io/tracking-id: argo-rollouts:apps/Deployment:argo-rollouts/argo-rollouts
      deployment.kubernetes.io/revision: "2"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"argo-rollouts:apps/Deployment:argo-rollouts/argo-rollouts"},"labels":{"app.kubernetes.io/component":"rollouts-controller","app.kubernetes.io/instance":"argo-rollouts","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"argo-rollouts","app.kubernetes.io/part-of":"argo-rollouts","app.kubernetes.io/version":"v1.7.2","helm.sh/chart":"argo-rollouts-2.38.0"},"name":"argo-rollouts","namespace":"argo-rollouts"},"spec":{"replicas":2,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app.kubernetes.io/component":"rollouts-controller","app.kubernetes.io/instance":"argo-rollouts","app.kubernetes.io/name":"argo-rollouts"}},"strategy":{"type":"RollingUpdate"},"template":{"metadata":{"labels":{"app.kubernetes.io/component":"rollouts-controller","app.kubernetes.io/instance":"argo-rollouts","app.kubernetes.io/name":"argo-rollouts"}},"spec":{"containers":[{"args":["--healthzPort=8080","--metricsport=8090","--loglevel=info","--logformat=text","--kloglevel=0","--leader-elect"],"image":"quay.io/argoproj/argo-rollouts:v1.7.2","imagePullPolicy":"IfNotPresent","livenessProbe":{"failureThreshold":3,"httpGet":{"path":"/healthz","port":"healthz"},"initialDelaySeconds":30,"periodSeconds":20,"successThreshold":1,"timeoutSeconds":10},"name":"argo-rollouts","ports":[{"containerPort":8090,"name":"metrics"},{"containerPort":8080,"name":"healthz"}],"readinessProbe":{"failureThreshold":3,"httpGet":{"path":"/metrics","port":"metrics"},"initialDelaySeconds":15,"periodSeconds":5,"successThreshold":1,"timeoutSeconds":4},"resources":{},"securityContext":{"allowPrivilegeEscalation":false,"capabilities":{"drop":["ALL"]},"readOnlyRootFilesystem":true,"seccompProfile":{"type":"RuntimeDefault"}},"volumeMounts":[{"mountPath":"/home/argo-rollouts/plugin-bin","name":"plugin-bin"},{"mountPath":"/tmp","name":"tmp"}]}],"securityContext":{"runAsNonRoot":true},"serviceAccountName":"argo-rollouts","volumes":[{"emptyDir":{},"name":"plugin-bin"},{"emptyDir":{},"name":"tmp"}]}}}}
    creationTimestamp: "2026-01-20T20:56:01Z"
    generation: 3
    labels:
      app.kubernetes.io/component: rollouts-controller
      app.kubernetes.io/instance: argo-rollouts
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: argo-rollouts
      app.kubernetes.io/part-of: argo-rollouts
      app.kubernetes.io/version: v1.7.2
      helm.sh/chart: argo-rollouts-2.38.0
    name: argo-rollouts
    namespace: argo-rollouts
    resourceVersion: "985993"
    uid: 6a880921-2a5e-4101-9c97-08dae5ce7974
  spec:
    progressDeadlineSeconds: 600
    replicas: 2
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app.kubernetes.io/component: rollouts-controller
        app.kubernetes.io/instance: argo-rollouts
        app.kubernetes.io/name: argo-rollouts
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        annotations:
          kubectl.kubernetes.io/restartedAt: "2026-01-22T02:35:50Z"
        labels:
          app.kubernetes.io/component: rollouts-controller
          app.kubernetes.io/instance: argo-rollouts
          app.kubernetes.io/name: argo-rollouts
      spec:
        containers:
        - args:
          - --healthzPort=8080
          - --metricsport=8090
          - --loglevel=info
          - --logformat=text
          - --kloglevel=0
          - --leader-elect
          image: quay.io/argoproj/argo-rollouts:v1.7.2
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: healthz
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 10
          name: argo-rollouts
          ports:
          - containerPort: 8090
            name: metrics
            protocol: TCP
          - containerPort: 8080
            name: healthz
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /metrics
              port: metrics
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 4
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            seccompProfile:
              type: RuntimeDefault
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /home/argo-rollouts/plugin-bin
            name: plugin-bin
          - mountPath: /tmp
            name: tmp
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext:
          runAsNonRoot: true
        serviceAccount: argo-rollouts
        serviceAccountName: argo-rollouts
        terminationGracePeriodSeconds: 30
        volumes:
        - emptyDir: {}
          name: plugin-bin
        - emptyDir: {}
          name: tmp
  status:
    availableReplicas: 2
    conditions:
    - lastTransitionTime: "2026-01-20T20:56:01Z"
      lastUpdateTime: "2026-01-22T02:36:45Z"
      message: ReplicaSet "argo-rollouts-6c44f5d6c5" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    - lastTransitionTime: "2026-01-28T05:33:38Z"
      lastUpdateTime: "2026-01-28T05:33:38Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    observedGeneration: 3
    readyReplicas: 2
    replicas: 2
    updatedReplicas: 2
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      argocd.argoproj.io/tracking-id: argo-rollouts:apps/Deployment:argo-rollouts/argo-rollouts-dashboard
      deployment.kubernetes.io/revision: "1"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"argo-rollouts:apps/Deployment:argo-rollouts/argo-rollouts-dashboard"},"labels":{"app.kubernetes.io/component":"rollouts-dashboard","app.kubernetes.io/instance":"argo-rollouts","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"argo-rollouts","app.kubernetes.io/part-of":"argo-rollouts","app.kubernetes.io/version":"v1.7.2","helm.sh/chart":"argo-rollouts-2.38.0"},"name":"argo-rollouts-dashboard","namespace":"argo-rollouts"},"spec":{"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app.kubernetes.io/component":"rollouts-dashboard","app.kubernetes.io/instance":"argo-rollouts","app.kubernetes.io/name":"argo-rollouts"}},"strategy":{"type":"Recreate"},"template":{"metadata":{"labels":{"app.kubernetes.io/component":"rollouts-dashboard","app.kubernetes.io/instance":"argo-rollouts","app.kubernetes.io/name":"argo-rollouts"}},"spec":{"containers":[{"args":["dashboard","--loglevel=info","--kloglevel=0"],"image":"quay.io/argoproj/kubectl-argo-rollouts:v1.7.2","imagePullPolicy":"IfNotPresent","name":"argo-rollouts-dashboard","ports":[{"containerPort":3100,"name":"dashboard"}],"resources":{},"securityContext":{}}],"securityContext":{"runAsNonRoot":true},"serviceAccountName":"argo-rollouts-dashboard"}}}}
    creationTimestamp: "2026-01-20T20:56:01Z"
    generation: 2
    labels:
      app.kubernetes.io/component: rollouts-dashboard
      app.kubernetes.io/instance: argo-rollouts
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: argo-rollouts
      app.kubernetes.io/part-of: argo-rollouts
      app.kubernetes.io/version: v1.7.2
      helm.sh/chart: argo-rollouts-2.38.0
    name: argo-rollouts-dashboard
    namespace: argo-rollouts
    resourceVersion: "907"
    uid: 2f3c243a-af08-4c39-8e1b-da611b50048e
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app.kubernetes.io/component: rollouts-dashboard
        app.kubernetes.io/instance: argo-rollouts
        app.kubernetes.io/name: argo-rollouts
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          app.kubernetes.io/component: rollouts-dashboard
          app.kubernetes.io/instance: argo-rollouts
          app.kubernetes.io/name: argo-rollouts
      spec:
        containers:
        - args:
          - dashboard
          - --loglevel=info
          - --kloglevel=0
          image: quay.io/argoproj/kubectl-argo-rollouts:v1.7.2
          imagePullPolicy: IfNotPresent
          name: argo-rollouts-dashboard
          ports:
          - containerPort: 3100
            name: dashboard
            protocol: TCP
          resources: {}
          securityContext: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext:
          runAsNonRoot: true
        serviceAccount: argo-rollouts-dashboard
        serviceAccountName: argo-rollouts-dashboard
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2026-01-20T20:56:01Z"
      lastUpdateTime: "2026-01-20T20:56:49Z"
      message: ReplicaSet "argo-rollouts-dashboard-fbdbfb68" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    - lastTransitionTime: "2026-01-27T04:38:23Z"
      lastUpdateTime: "2026-01-27T04:38:23Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    observedGeneration: 2
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
kind: List
metadata:
  resourceVersion: ""
