apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"bookforge","namespace":"default"},"spec":{"ports":[{"port":80,"targetPort":8080}],"selector":{"app":"bookforge"},"type":"ClusterIP"}}
    creationTimestamp: "2026-01-19T13:51:33Z"
    name: bookforge
    namespace: default
    resourceVersion: "10148"
    uid: b2b72d7e-450a-4faa-b8b3-5c9b1ae6eaa7
  spec:
    clusterIP: 10.43.165.207
    clusterIPs:
    - 10.43.165.207
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
    selector:
      app: bookforge
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      argocd.argoproj.io/tracking-id: lenovo-services:/Service:default/bookforge-external
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"lenovo-services:/Service:default/bookforge-external"},"labels":{"app":"bookforge","type":"external"},"name":"bookforge-external","namespace":"default"},"spec":{"ports":[{"name":"http","port":8080,"protocol":"TCP","targetPort":8080}],"type":"ClusterIP"}}
    creationTimestamp: "2026-01-19T13:51:32Z"
    labels:
      app: bookforge
      type: external
    name: bookforge-external
    namespace: default
    resourceVersion: "10149"
    uid: dc91f32b-1dc5-4f88-994e-06766aeb0a66
  spec:
    clusterIP: 10.43.170.226
    clusterIPs:
    - 10.43.170.226
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"bookforge-nodeport","namespace":"default"},"spec":{"ports":[{"nodePort":30808,"port":80,"targetPort":8080}],"selector":{"app":"bookforge"},"type":"NodePort"}}
    creationTimestamp: "2026-01-19T13:51:32Z"
    name: bookforge-nodeport
    namespace: default
    resourceVersion: "10150"
    uid: 3d99a98c-26e3-4bde-bbd7-95d9a080d6ff
  spec:
    clusterIP: 10.43.225.28
    clusterIPs:
    - 10.43.225.28
    externalTrafficPolicy: Cluster
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - nodePort: 30808
      port: 80
      protocol: TCP
      targetPort: 8080
    selector:
      app: bookforge
    sessionAffinity: None
    type: NodePort
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      argocd.argoproj.io/tracking-id: cmd-api:/Service:default/cmd-api
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"cmd-api:/Service:default/cmd-api"},"labels":{"app.kubernetes.io/instance":"cmd-api","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"cmd-api","app.kubernetes.io/version":"1.0.0","helm.sh/chart":"cmd-api-1.0.0"},"name":"cmd-api","namespace":"default"},"spec":{"ports":[{"port":80,"protocol":"TCP","targetPort":3000}],"selector":{"app":"cmd-api","app.kubernetes.io/instance":"cmd-api","app.kubernetes.io/name":"cmd-api"},"type":"ClusterIP"}}
    creationTimestamp: "2026-01-20T07:09:30Z"
    labels:
      app.kubernetes.io/instance: cmd-api
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: cmd-api
      app.kubernetes.io/version: 1.0.0
      helm.sh/chart: cmd-api-1.0.0
    name: cmd-api
    namespace: default
    resourceVersion: "10151"
    uid: 7c2812e3-c43b-471b-a06d-35fbec7319d6
  spec:
    clusterIP: 10.43.170.9
    clusterIPs:
    - 10.43.170.9
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
    selector:
      app: cmd-api
      app.kubernetes.io/instance: cmd-api
      app.kubernetes.io/name: cmd-api
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: "2026-01-15T14:50:08Z"
    labels:
      component: apiserver
      provider: kubernetes
    name: kubernetes
    namespace: default
    resourceVersion: "10152"
    uid: 2158805d-0610-4169-8ae6-aec270ee90e6
  spec:
    clusterIP: 10.43.0.1
    clusterIPs:
    - 10.43.0.1
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 6443
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      argocd.argoproj.io/tracking-id: lenovo-services:/Service:default/ollama-external
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"lenovo-services:/Service:default/ollama-external"},"labels":{"app":"ollama","type":"external"},"name":"ollama-external","namespace":"default"},"spec":{"ports":[{"name":"http","port":11434,"protocol":"TCP","targetPort":11434}],"type":"ClusterIP"}}
    creationTimestamp: "2026-01-19T13:51:32Z"
    labels:
      app: ollama
      type: external
    name: ollama-external
    namespace: default
    resourceVersion: "10153"
    uid: 3577a2f2-2441-41a5-9757-4f5122016d9d
  spec:
    clusterIP: 10.43.172.224
    clusterIPs:
    - 10.43.172.224
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http
      port: 11434
      protocol: TCP
      targetPort: 11434
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      argocd.argoproj.io/tracking-id: lenovo-services:/Service:default/ollama-nodeport
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"lenovo-services:/Service:default/ollama-nodeport"},"labels":{"app":"ollama","type":"external"},"name":"ollama-nodeport","namespace":"default"},"spec":{"ports":[{"name":"http","nodePort":31434,"port":11434,"protocol":"TCP","targetPort":11434}],"selector":{},"type":"NodePort"}}
    creationTimestamp: "2026-01-19T13:51:32Z"
    labels:
      app: ollama
      type: external
    name: ollama-nodeport
    namespace: default
    resourceVersion: "10154"
    uid: 841a4ecc-9e8a-4017-b870-aaec09fa58a3
  spec:
    clusterIP: 10.43.234.241
    clusterIPs:
    - 10.43.234.241
    externalTrafficPolicy: Cluster
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http
      nodePort: 31434
      port: 11434
      protocol: TCP
      targetPort: 11434
    sessionAffinity: None
    type: NodePort
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"postgres","namespace":"default"},"spec":{"ports":[{"port":5432,"targetPort":5432}],"selector":{"app":"postgres"},"type":"ClusterIP"}}
    creationTimestamp: "2026-01-19T22:20:25Z"
    name: postgres
    namespace: default
    resourceVersion: "10155"
    uid: 1e640fd5-144f-40cc-ad60-c8b75d65ff67
  spec:
    clusterIP: 10.43.81.250
    clusterIPs:
    - 10.43.81.250
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
    selector:
      app: postgres
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      argocd.argoproj.io/tracking-id: vaultwarden:/Service:default/vaultwarden
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"vaultwarden:/Service:default/vaultwarden"},"labels":{"app":"vaultwarden"},"name":"vaultwarden","namespace":"default"},"spec":{"ports":[{"name":"http","port":80,"targetPort":80},{"name":"websocket","port":3012,"targetPort":3012}],"selector":{"app":"vaultwarden"},"type":"ClusterIP"}}
    creationTimestamp: "2026-01-20T10:13:14Z"
    labels:
      app: vaultwarden
    name: vaultwarden
    namespace: default
    resourceVersion: "10156"
    uid: c65dccd9-fab7-4616-92a2-55bec3fc646c
  spec:
    clusterIP: 10.43.27.243
    clusterIPs:
    - 10.43.27.243
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
    - name: websocket
      port: 3012
      protocol: TCP
      targetPort: 3012
    selector:
      app: vaultwarden
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      argocd.argoproj.io/tracking-id: vaultwarden:/Service:default/vaultwarden-nodeport
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"vaultwarden:/Service:default/vaultwarden-nodeport"},"labels":{"app":"vaultwarden"},"name":"vaultwarden-nodeport","namespace":"default"},"spec":{"ports":[{"name":"http","nodePort":30880,"port":80,"targetPort":80}],"selector":{"app":"vaultwarden"},"type":"NodePort"}}
    creationTimestamp: "2026-01-20T10:13:14Z"
    labels:
      app: vaultwarden
    name: vaultwarden-nodeport
    namespace: default
    resourceVersion: "10157"
    uid: dcb0df50-7aef-4609-8ee6-f3b98bdddea8
  spec:
    clusterIP: 10.43.185.198
    clusterIPs:
    - 10.43.185.198
    externalTrafficPolicy: Cluster
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http
      nodePort: 30880
      port: 80
      protocol: TCP
      targetPort: 80
    selector:
      app: vaultwarden
    sessionAffinity: None
    type: NodePort
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
