apiVersion: v1
items:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    annotations:
      argocd.argoproj.io/tracking-id: argo-rollouts:/ConfigMap:argo-rollouts/argo-rollouts-config
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","data":null,"kind":"ConfigMap","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"argo-rollouts:/ConfigMap:argo-rollouts/argo-rollouts-config"},"labels":{"app.kubernetes.io/component":"rollouts-controller","app.kubernetes.io/instance":"argo-rollouts","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"argo-rollouts","app.kubernetes.io/part-of":"argo-rollouts","app.kubernetes.io/version":"v1.7.2","helm.sh/chart":"argo-rollouts-2.38.0"},"name":"argo-rollouts-config","namespace":"argo-rollouts"}}
    creationTimestamp: "2026-01-20T20:55:57Z"
    labels:
      app.kubernetes.io/component: rollouts-controller
      app.kubernetes.io/instance: argo-rollouts
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: argo-rollouts
      app.kubernetes.io/part-of: argo-rollouts
      app.kubernetes.io/version: v1.7.2
      helm.sh/chart: argo-rollouts-2.38.0
    name: argo-rollouts-config
    namespace: argo-rollouts
    resourceVersion: "690"
    uid: 52894ec3-8b74-496a-85c4-99da529d110b
- apiVersion: v1
  kind: ConfigMap
  metadata:
    annotations:
      argocd.argoproj.io/tracking-id: argo-rollouts:/ConfigMap:argo-rollouts/argo-rollouts-notification-configmap
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","data":null,"kind":"ConfigMap","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"argo-rollouts:/ConfigMap:argo-rollouts/argo-rollouts-notification-configmap"},"labels":{"app.kubernetes.io/component":"rollouts-controller","app.kubernetes.io/instance":"argo-rollouts","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"argo-rollouts","app.kubernetes.io/part-of":"argo-rollouts","app.kubernetes.io/version":"v1.7.2","helm.sh/chart":"argo-rollouts-2.38.0"},"name":"argo-rollouts-notification-configmap","namespace":"argo-rollouts"}}
    creationTimestamp: "2026-01-20T20:55:57Z"
    labels:
      app.kubernetes.io/component: rollouts-controller
      app.kubernetes.io/instance: argo-rollouts
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: argo-rollouts
      app.kubernetes.io/part-of: argo-rollouts
      app.kubernetes.io/version: v1.7.2
      helm.sh/chart: argo-rollouts-2.38.0
    name: argo-rollouts-notification-configmap
    namespace: argo-rollouts
    resourceVersion: "691"
    uid: 8729a6fc-a76c-4cfb-b1d9-098ae7b7ff3d
- apiVersion: v1
  data:
    ca.crt: |
      -----BEGIN CERTIFICATE-----
      MIIBdjCCAR2gAwIBAgIBADAKBggqhkjOPQQDAjAjMSEwHwYDVQQDDBhrM3Mtc2Vy
      dmVyLWNhQDE3Njg0ODg1OTUwHhcNMjYwMTE1MTQ0OTU1WhcNMzYwMTEzMTQ0OTU1
      WjAjMSEwHwYDVQQDDBhrM3Mtc2VydmVyLWNhQDE3Njg0ODg1OTUwWTATBgcqhkjO
      PQIBBggqhkjOPQMBBwNCAAS5M3qca7X6I+z9JEP6m2z24D0Vxp/N9riBEnGH45Cd
      2BskCdidQJnMjVhm+Cb/XskOINIf6xwmtSvUe0yvjF1eo0IwQDAOBgNVHQ8BAf8E
      BAMCAqQwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUirW/RlF+LEjL/PJV27md
      5o8hlsUwCgYIKoZIzj0EAwIDRwAwRAIgWFi90tm3iGOxztyDXsQS5Xmt3KWl3hX5
      GVkFVp7VWrYCIH350uTqoqKYVuEL3AXTToIVryQVnEEUCxKpDRVjLsm9
      -----END CERTIFICATE-----
  kind: ConfigMap
  metadata:
    annotations:
      kubernetes.io/description: Contains a CA bundle that can be used to verify the
        kube-apiserver when using internal endpoints such as the internal service
        IP or kubernetes.default.svc. No other usage is guaranteed across distributions
        of Kubernetes clusters.
    creationTimestamp: "2026-01-20T20:55:46Z"
    name: kube-root-ca.crt
    namespace: argo-rollouts
    resourceVersion: "692"
    uid: b12ae10e-558f-446a-9a79-5fdeefde7b1f
kind: List
metadata:
  resourceVersion: ""
