apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      argocd.argoproj.io/tracking-id: argo-rollouts:/Service:argo-rollouts/argo-rollouts-dashboard
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"argo-rollouts:/Service:argo-rollouts/argo-rollouts-dashboard"},"labels":{"app.kubernetes.io/component":"rollouts-dashboard","app.kubernetes.io/instance":"argo-rollouts","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"argo-rollouts","app.kubernetes.io/part-of":"argo-rollouts","app.kubernetes.io/version":"v1.7.2","helm.sh/chart":"argo-rollouts-2.38.0"},"name":"argo-rollouts-dashboard","namespace":"argo-rollouts"},"spec":{"ports":[{"name":"dashboard","port":3100,"protocol":"TCP","targetPort":3100}],"selector":{"app.kubernetes.io/component":"rollouts-dashboard","app.kubernetes.io/instance":"argo-rollouts","app.kubernetes.io/name":"argo-rollouts"},"type":"ClusterIP"}}
    creationTimestamp: "2026-01-20T20:56:01Z"
    labels:
      app.kubernetes.io/component: rollouts-dashboard
      app.kubernetes.io/instance: argo-rollouts
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: argo-rollouts
      app.kubernetes.io/part-of: argo-rollouts
      app.kubernetes.io/version: v1.7.2
      helm.sh/chart: argo-rollouts-2.38.0
    name: argo-rollouts-dashboard
    namespace: argo-rollouts
    resourceVersion: "10137"
    uid: ca91d11e-f66b-46a2-a2ad-251946350bfa
  spec:
    clusterIP: 10.43.240.4
    clusterIPs:
    - 10.43.240.4
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: dashboard
      port: 3100
      protocol: TCP
      targetPort: 3100
    selector:
      app.kubernetes.io/component: rollouts-dashboard
      app.kubernetes.io/instance: argo-rollouts
      app.kubernetes.io/name: argo-rollouts
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
