apiVersion: apps/v1
kind: Deployment
metadata:
  name: holm-cli
  namespace: holm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: holm-cli
  template:
    metadata:
      labels:
        app: holm-cli
    spec:
      nodeSelector:
        kubernetes.io/arch: arm64
      containers:
      - name: holm-cli
        image: registry.holm.svc.cluster.local:5000/holm/holm-cli:v1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: holm-cli
  namespace: holm
spec:
  selector:
    app: holm-cli
  ports:
  - port: 8080
    targetPort: 8080
