apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      argocd.argoproj.io/tracking-id: searxng:/Service:searxng/searxng
      gethomepage.dev/description: Privacy Search Engine
      gethomepage.dev/enabled: "true"
      gethomepage.dev/group: Applications
      gethomepage.dev/href: https://search.holm.chat
      gethomepage.dev/icon: searxng.svg
      gethomepage.dev/name: SearXNG
    creationTimestamp: "2026-01-20T07:50:46Z"
    labels:
      app.kubernetes.io/instance: searxng
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: searxng
      app.kubernetes.io/version: latest
      helm.sh/chart: searxng-1.0.1
    name: searxng
    namespace: searxng
    resourceVersion: "10289"
    uid: 79e5917e-99fd-400e-8e16-390fdbbc4f72
  spec:
    clusterIP: 10.43.76.152
    clusterIPs:
    - 10.43.76.152
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http
    selector:
      app.kubernetes.io/instance: searxng
      app.kubernetes.io/name: searxng
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      argocd.argoproj.io/tracking-id: searxng:/Service:searxng/searxng-redis
    creationTimestamp: "2026-01-20T07:45:47Z"
    labels:
      app.kubernetes.io/instance: searxng
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: redis
      app.kubernetes.io/version: 6.2.6
      helm.sh/chart: redis-0.0.3
    name: searxng-redis
    namespace: searxng
    resourceVersion: "10290"
    uid: 12580bbe-8daa-4fbe-8beb-7eee7724d22f
  spec:
    clusterIP: 10.43.176.165
    clusterIPs:
    - 10.43.176.165
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http
      port: 6379
      protocol: TCP
      targetPort: http
    selector:
      app.kubernetes.io/instance: searxng
      app.kubernetes.io/name: redis
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
