apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: docs-site
  namespace: docs
  labels:
    app.kubernetes.io/name: docs-site
    app.kubernetes.io/part-of: holm-chat
spec:
  hostnames:
    - holm.chat
    - www.holm.chat
  parentRefs:
    - name: main-gateway
      namespace: default
  rules:
    - backendRefs:
        - name: docs-site
          port: 80
      matches:
        - path:
            type: PathPrefix
            value: /
