apiVersion: v1
items:
- apiVersion: v1
  data:
    inventory.ini: |
      [all]
      rpi-1 ansible_host=192.168.8.197
      rpi-2 ansible_host=192.168.8.196
      rpi-3 ansible_host=192.168.8.195
      rpi-4 ansible_host=192.168.8.194
      rpi-5 ansible_host=192.168.8.108
      rpi-6 ansible_host=192.168.8.235
      rpi-7 ansible_host=192.168.8.209
      rpi-8 ansible_host=192.168.8.202
      rpi-9 ansible_host=192.168.8.187
      rpi-10 ansible_host=192.168.8.210
      rpi-11 ansible_host=192.168.8.231
      rpi-12 ansible_host=192.168.8.105
      cm3588-plus ansible_host=192.168.8.152

      [control_plane]
      rpi-1

      [workers]
      rpi-2
      rpi-3
      rpi-4
      rpi-5
      rpi-6
      rpi-7
      rpi-8
      rpi-9
      rpi-10
      rpi-11
      rpi-12
      cm3588-plus

      [all:vars]
      ansible_user=rpi1
      ansible_python_interpreter=/usr/bin/python3
      ansible_ssh_common_args='-o StrictHostKeyChecking=no'
  kind: ConfigMap
  metadata:
    annotations:
      argocd.argoproj.io/tracking-id: animus-dashboard:/ConfigMap:animus/animus-ansible-inventory
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","data":{"inventory.ini":"[all]\nrpi-1 ansible_host=192.168.8.197\nrpi-2 ansible_host=192.168.8.196\nrpi-3 ansible_host=192.168.8.195\nrpi-4 ansible_host=192.168.8.194\nrpi-5 ansible_host=192.168.8.108\nrpi-6 ansible_host=192.168.8.235\nrpi-7 ansible_host=192.168.8.209\nrpi-8 ansible_host=192.168.8.202\nrpi-9 ansible_host=192.168.8.187\nrpi-10 ansible_host=192.168.8.210\nrpi-11 ansible_host=192.168.8.231\nrpi-12 ansible_host=192.168.8.105\ncm3588-plus ansible_host=192.168.8.152\n\n[control_plane]\nrpi-1\n\n[workers]\nrpi-2\nrpi-3\nrpi-4\nrpi-5\nrpi-6\nrpi-7\nrpi-8\nrpi-9\nrpi-10\nrpi-11\nrpi-12\ncm3588-plus\n\n[all:vars]\nansible_user=rpi1\nansible_python_interpreter=/usr/bin/python3\nansible_ssh_common_args='-o StrictHostKeyChecking=no'\n"},"kind":"ConfigMap","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"animus-dashboard:/ConfigMap:animus/animus-ansible-inventory"},"labels":{"app.kubernetes.io/name":"animus-dashboard"},"name":"animus-ansible-inventory","namespace":"animus"}}
    creationTimestamp: "2026-01-26T01:32:04Z"
    labels:
      app.kubernetes.io/name: animus-dashboard
    name: animus-ansible-inventory
    namespace: animus
    resourceVersion: "685"
    uid: e4063767-2952-4eea-a7a4-c9eedf9eb0e6
- apiVersion: v1
  data:
    ca.crt: |
      -----BEGIN CERTIFICATE-----
      MIIBdjCCAR2gAwIBAgIBADAKBggqhkjOPQQDAjAjMSEwHwYDVQQDDBhrM3Mtc2Vy
      dmVyLWNhQDE3Njg0ODg1OTUwHhcNMjYwMTE1MTQ0OTU1WhcNMzYwMTEzMTQ0OTU1
      WjAjMSEwHwYDVQQDDBhrM3Mtc2VydmVyLWNhQDE3Njg0ODg1OTUwWTATBgcqhkjO
      PQIBBggqhkjOPQMBBwNCAAS5M3qca7X6I+z9JEP6m2z24D0Vxp/N9riBEnGH45Cd
      2BskCdidQJnMjVhm+Cb/XskOINIf6xwmtSvUe0yvjF1eo0IwQDAOBgNVHQ8BAf8E
      BAMCAqQwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUirW/RlF+LEjL/PJV27md
      5o8hlsUwCgYIKoZIzj0EAwIDRwAwRAIgWFi90tm3iGOxztyDXsQS5Xmt3KWl3hX5
      GVkFVp7VWrYCIH350uTqoqKYVuEL3AXTToIVryQVnEEUCxKpDRVjLsm9
      -----END CERTIFICATE-----
  kind: ConfigMap
  metadata:
    annotations:
      kubernetes.io/description: Contains a CA bundle that can be used to verify the
        kube-apiserver when using internal endpoints such as the internal service
        IP or kubernetes.default.svc. No other usage is guaranteed across distributions
        of Kubernetes clusters.
    creationTimestamp: "2026-01-26T01:32:03Z"
    name: kube-root-ca.crt
    namespace: animus
    resourceVersion: "686"
    uid: f8f95af9-3e96-4461-850d-2da03aa9dee3
kind: List
metadata:
  resourceVersion: ""
