apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      argocd.argoproj.io/tracking-id: animus-dashboard:/Service:animus/animus-api
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"animus-dashboard:/Service:animus/animus-api"},"labels":{"app.kubernetes.io/component":"api","app.kubernetes.io/name":"animus-dashboard"},"name":"animus-api","namespace":"animus"},"spec":{"ports":[{"name":"http","port":8080,"protocol":"TCP","targetPort":"http"}],"selector":{"app.kubernetes.io/component":"api","app.kubernetes.io/name":"animus-dashboard"},"type":"ClusterIP"}}
    creationTimestamp: "2026-01-26T01:32:05Z"
    labels:
      app.kubernetes.io/component: api
      app.kubernetes.io/name: animus-dashboard
    name: animus-api
    namespace: animus
    resourceVersion: "10134"
    uid: 6893abdd-103a-4cba-a5fa-232398db7452
  spec:
    clusterIP: 10.43.134.70
    clusterIPs:
    - 10.43.134.70
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http
    selector:
      app.kubernetes.io/component: api
      app.kubernetes.io/name: animus-dashboard
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      argocd.argoproj.io/tracking-id: animus-dashboard:/Service:animus/animus-frontend
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"animus-dashboard:/Service:animus/animus-frontend"},"labels":{"app.kubernetes.io/component":"frontend","app.kubernetes.io/name":"animus-dashboard"},"name":"animus-frontend","namespace":"animus"},"spec":{"ports":[{"name":"http","port":3000,"protocol":"TCP","targetPort":"http"}],"selector":{"app.kubernetes.io/component":"frontend","app.kubernetes.io/name":"animus-dashboard"},"type":"ClusterIP"}}
    creationTimestamp: "2026-01-26T01:32:06Z"
    labels:
      app.kubernetes.io/component: frontend
      app.kubernetes.io/name: animus-dashboard
    name: animus-frontend
    namespace: animus
    resourceVersion: "10135"
    uid: 7cca56d7-d82e-44a1-ab20-2e67f9af8ec1
  spec:
    clusterIP: 10.43.83.201
    clusterIPs:
    - 10.43.83.201
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http
      port: 3000
      protocol: TCP
      targetPort: http
    selector:
      app.kubernetes.io/component: frontend
      app.kubernetes.io/name: animus-dashboard
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
