apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: "2026-01-25T02:55:58Z"
    labels:
      app.kubernetes.io/component: admission-webhooks
      app.kubernetes.io/created-by: keda
      app.kubernetes.io/instance: admission-webhooks
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/part-of: keda-operator
      app.kubernetes.io/version: 2.13.0
    name: keda-admission-webhooks
    namespace: keda
    resourceVersion: "10243"
    uid: 70c3d5a2-27ff-43bb-86be-0d976c77e324
  spec:
    clusterIP: 10.43.23.34
    clusterIPs:
    - 10.43.23.34
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 9443
    - name: metrics
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: keda-admission-webhooks
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: "2026-01-25T02:55:58Z"
    labels:
      app.kubernetes.io/name: keda-metrics-apiserver
      app.kubernetes.io/part-of: keda-operator
      app.kubernetes.io/version: 2.13.0
    name: keda-metrics-apiserver
    namespace: keda
    resourceVersion: "10244"
    uid: 695ef55d-9b42-4d69-abd0-505636c51127
  spec:
    clusterIP: 10.43.240.78
    clusterIPs:
    - 10.43.240.78
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 6443
    - name: metrics
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: keda-metrics-apiserver
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: "2026-01-25T02:55:58Z"
    labels:
      app.kubernetes.io/name: keda-operator
      app.kubernetes.io/part-of: keda-operator
      app.kubernetes.io/version: 2.13.0
    name: keda-operator
    namespace: keda
    resourceVersion: "10245"
    uid: 5bb60218-503f-42a3-9ca4-cc1bb265b098
  spec:
    clusterIP: 10.43.113.45
    clusterIPs:
    - 10.43.113.45
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: metricsservice
      port: 9666
      protocol: TCP
      targetPort: 9666
    - name: metrics
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: keda-operator
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
