apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      resource-spec-hash: "713456839"
    creationTimestamp: "2026-01-22T02:14:10Z"
    labels:
      controller: eventbus-controller
      eventbus-name: default
      owner-name: default
      stan: "yes"
    name: eventbus-default-stan-svc
    namespace: argo-events
    ownerReferences:
    - apiVersion: argoproj.io/v1alpha1
      blockOwnerDeletion: true
      controller: true
      kind: EventBus
      name: default
      uid: 27b873f3-1a79-4fba-bbb4-4268601345c2
    resourceVersion: "10136"
    uid: 852f8ffe-da88-44e8-a9a5-ef7029c8a07f
  spec:
    clusterIP: None
    clusterIPs:
    - None
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: tcp-client
      port: 4222
      protocol: TCP
      targetPort: 4222
    - name: cluster
      port: 6222
      protocol: TCP
      targetPort: 6222
    - name: monitor
      port: 8222
      protocol: TCP
      targetPort: 8222
    selector:
      controller: eventbus-controller
      eventbus-name: default
      owner-name: default
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
