apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: "2026-01-25T01:01:27Z"
    labels:
      app: controller.csi.trident.qnap.io
      k8s_version: v1.34.3
      trident_version: v1.06.0
    name: trident-csi
    namespace: trident
    ownerReferences:
    - apiVersion: trident.qnap.io/v1
      controller: true
      kind: TridentOrchestrator
      name: trident
      uid: 8a0bec38-8bff-4828-ae27-2ef74058714d
    resourceVersion: "10303"
    uid: e4fd20f5-e20b-4ac1-8e6a-878e19820f0e
  spec:
    clusterIP: 10.43.239.153
    clusterIPs:
    - 10.43.239.153
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: https
      port: 34571
      protocol: TCP
      targetPort: 8443
    - name: metrics
      port: 9220
      protocol: TCP
      targetPort: 8001
    selector:
      app: controller.csi.trident.qnap.io
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
