apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: chat-hub-hpa
  namespace: holm
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: chat-hub
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: auth-gateway-hpa
  namespace: holm
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: auth-gateway
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: terminal-web-hpa
  namespace: holm
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: terminal-web
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: file-web-nautilus-hpa
  namespace: holm
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: file-web-nautilus
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
