apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"grocy"},"name":"grocy","namespace":"grocy"},"spec":{"ports":[{"name":"http","port":80,"targetPort":80}],"selector":{"app":"grocy"},"type":"ClusterIP"}}
    creationTimestamp: "2026-01-24T23:32:09Z"
    labels:
      app: grocy
    name: grocy
    namespace: grocy
    resourceVersion: "10160"
    uid: 9df9a4c4-41c9-43a6-afb2-a74284964b31
  spec:
    clusterIP: 10.43.2.143
    clusterIPs:
    - 10.43.2.143
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
    selector:
      app: grocy
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      gethomepage.dev/description: Household Management
      gethomepage.dev/enabled: "true"
      gethomepage.dev/group: Local Apps
      gethomepage.dev/href: http://192.168.8.197:30881
      gethomepage.dev/icon: grocy.svg
      gethomepage.dev/name: Grocy
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"gethomepage.dev/description":"Household Management","gethomepage.dev/enabled":"true","gethomepage.dev/group":"Local Apps","gethomepage.dev/href":"http://192.168.8.197:30881","gethomepage.dev/icon":"grocy.svg","gethomepage.dev/name":"Grocy"},"labels":{"app":"grocy"},"name":"grocy-nodeport","namespace":"grocy"},"spec":{"ports":[{"name":"http","nodePort":30881,"port":80,"targetPort":80}],"selector":{"app":"grocy"},"type":"NodePort"}}
    creationTimestamp: "2026-01-24T23:32:09Z"
    labels:
      app: grocy
    name: grocy-nodeport
    namespace: grocy
    resourceVersion: "10161"
    uid: 3eeba038-2050-4b45-808e-70025eaf4902
  spec:
    clusterIP: 10.43.200.117
    clusterIPs:
    - 10.43.200.117
    externalTrafficPolicy: Cluster
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http
      nodePort: 30881
      port: 80
      protocol: TCP
      targetPort: 80
    selector:
      app: grocy
    sessionAffinity: None
    type: NodePort
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
