apiVersion: v1
kind: Secret
metadata:
  name: auth-jwt-secret
  namespace: holm
type: Opaque
stringData:
  secret: "CHANGE_ME_IN_CLUSTER"
---
apiVersion: v1
kind: Secret
metadata:
  name: auth-admin-secret
  namespace: holm
type: Opaque
stringData:
  password: "CHANGE_ME_IN_CLUSTER"
