apiVersion: v1
kind: Secret
metadata:
  name: user-preferences-db-secret
  namespace: holm
type: Opaque
stringData:
  database-url: "postgres://holm:CHANGE_ME_IN_CLUSTER@postgres.holm.svc.cluster.local:5432/holm?sslmode=disable"
