apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-move
  namespace: holm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file-move
  template:
    metadata:
      labels:
        app: file-move
    spec:
      nodeSelector:
        kubernetes.io/arch: arm64
      containers:
      - name: file-move
        image: registry.holm.svc.cluster.local:5000/holm/file-move:v1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: file-move
  namespace: holm
spec:
  selector:
    app: file-move
  ports:
  - port: 8080
    targetPort: 8080
