apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      argocd.argoproj.io/tracking-id: kubeview:/Service:kubeview/kubeview
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"kubeview:/Service:kubeview/kubeview"},"labels":{"app.kubernetes.io/instance":"kubeview","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"kubeview","app.kubernetes.io/version":"2.1.1","helm.sh/chart":"kubeview-2.0.6"},"name":"kubeview","namespace":"kubeview"},"spec":{"ports":[{"name":"http","port":8000,"protocol":"TCP","targetPort":8000}],"selector":{"app.kubernetes.io/instance":"kubeview","app.kubernetes.io/name":"kubeview"},"type":"ClusterIP"}}
    creationTimestamp: "2026-01-20T02:13:47Z"
    labels:
      app.kubernetes.io/instance: kubeview
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: kubeview
      app.kubernetes.io/version: 2.1.1
      helm.sh/chart: kubeview-2.0.6
    name: kubeview
    namespace: kubeview
    resourceVersion: "10255"
    uid: decc412e-d0cc-4f13-acb6-744e3d12625e
  spec:
    clusterIP: 10.43.108.190
    clusterIPs:
    - 10.43.108.190
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http
      port: 8000
      protocol: TCP
      targetPort: 8000
    selector:
      app.kubernetes.io/instance: kubeview
      app.kubernetes.io/name: kubeview
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
