apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "6"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"livekit","namespace":"livekit"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"livekit"}},"template":{"metadata":{"labels":{"app":"livekit"}},"spec":{"containers":[{"args":["--config","/etc/livekit/config.yaml"],"env":[{"name":"LIVEKIT_PORT","value":"7880"}],"image":"livekit/livekit-server:latest","name":"livekit","ports":[{"containerPort":7880,"name":"http"},{"containerPort":7881,"name":"rtc-tcp"},{"containerPort":3478,"name":"turn-udp","protocol":"UDP"}],"resources":{"limits":{"cpu":"2","memory":"1Gi"},"requests":{"cpu":"100m","memory":"256Mi"}},"volumeMounts":[{"mountPath":"/etc/livekit","name":"config"}]}],"volumes":[{"configMap":{"name":"livekit-config"},"name":"config"}]}}}}
    creationTimestamp: "2026-01-25T20:19:11Z"
    generation: 6
    name: livekit
    namespace: livekit
    resourceVersion: "1015"
    uid: 5c96fdca-9e55-4696-9dc2-0c3056569109
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: livekit
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        annotations:
          kubectl.kubernetes.io/restartedAt: "2026-01-25T12:56:54-08:00"
        labels:
          app: livekit
      spec:
        containers:
        - args:
          - --config
          - /etc/livekit/config.yaml
          env:
          - name: LIVEKIT_PORT
            value: "7880"
          image: livekit/livekit-server:latest
          imagePullPolicy: Always
          name: livekit
          ports:
          - containerPort: 7880
            name: http
            protocol: TCP
          - containerPort: 7881
            name: rtc-tcp
            protocol: TCP
          - containerPort: 3478
            name: turn-udp
            protocol: UDP
          resources:
            limits:
              cpu: "2"
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 256Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /etc/livekit
            name: config
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - configMap:
            defaultMode: 420
            name: livekit-config
          name: config
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2026-01-25T20:19:11Z"
      lastUpdateTime: "2026-01-25T20:56:57Z"
      message: ReplicaSet "livekit-59789fc95d" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    - lastTransitionTime: "2026-01-27T02:39:12Z"
      lastUpdateTime: "2026-01-27T02:39:12Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    observedGeneration: 6
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "4"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"livekit-jwt","namespace":"livekit"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"livekit-jwt"}},"template":{"metadata":{"labels":{"app":"livekit-jwt"}},"spec":{"containers":[{"env":[{"name":"LIVEKIT_URL","value":"wss://livekit.holm.chat"},{"name":"LIVEKIT_KEY","value":"APIcc1c451a77001d8dc347"},{"name":"LIVEKIT_SECRET","value":"9324e740ab1b2bd5b53b14c798f5c2dde7dbfe996230f967f29d17cc04aa5624"},{"name":"LIVEKIT_JWT_PORT","value":""},{"name":"LIVEKIT_JWT_BIND","value":":8080"}],"image":"ghcr.io/element-hq/lk-jwt-service:latest","name":"livekit-jwt","ports":[{"containerPort":8080}]}]}}}}
    creationTimestamp: "2026-01-25T20:22:11Z"
    generation: 4
    name: livekit-jwt
    namespace: livekit
    resourceVersion: "1016"
    uid: 0a8af777-16e5-40b0-9245-f20b68e33aaf
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: livekit-jwt
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        labels:
          app: livekit-jwt
      spec:
        containers:
        - env:
          - name: LIVEKIT_URL
            value: wss://livekit.holm.chat
          - name: LIVEKIT_KEY
            value: APIcc1c451a77001d8dc347
          - name: LIVEKIT_SECRET
            value: 9324e740ab1b2bd5b53b14c798f5c2dde7dbfe996230f967f29d17cc04aa5624
          - name: LIVEKIT_JWT_PORT
          - name: LIVEKIT_JWT_BIND
            value: :8080
          image: ghcr.io/element-hq/lk-jwt-service:latest
          imagePullPolicy: Always
          name: livekit-jwt
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2026-01-25T20:22:11Z"
      lastUpdateTime: "2026-01-25T20:32:49Z"
      message: ReplicaSet "livekit-jwt-68797995df" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    - lastTransitionTime: "2026-01-27T04:38:43Z"
      lastUpdateTime: "2026-01-27T04:38:43Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    observedGeneration: 4
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "3"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"livekit-proxy","namespace":"livekit"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"livekit-proxy"}},"template":{"metadata":{"labels":{"app":"livekit-proxy"}},"spec":{"containers":[{"image":"nginx:alpine","name":"nginx","ports":[{"containerPort":7880}],"volumeMounts":[{"mountPath":"/etc/nginx/nginx.conf","name":"config","subPath":"nginx.conf"}]}],"volumes":[{"configMap":{"name":"livekit-proxy-config"},"name":"config"}]}}}}
    creationTimestamp: "2026-01-25T20:32:18Z"
    generation: 3
    name: livekit-proxy
    namespace: livekit
    resourceVersion: "1017"
    uid: 3b17ad20-8931-4014-9604-a7c4c02ba91b
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: livekit-proxy
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        annotations:
          kubectl.kubernetes.io/restartedAt: "2026-01-25T12:34:42-08:00"
        labels:
          app: livekit-proxy
      spec:
        containers:
        - image: nginx:alpine
          imagePullPolicy: IfNotPresent
          name: nginx
          ports:
          - containerPort: 7880
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /etc/nginx/nginx.conf
            name: config
            subPath: nginx.conf
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - configMap:
            defaultMode: 420
            name: livekit-proxy-config
          name: config
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2026-01-25T20:32:18Z"
      lastUpdateTime: "2026-01-25T20:34:47Z"
      message: ReplicaSet "livekit-proxy-84c678485c" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    - lastTransitionTime: "2026-01-27T01:12:47Z"
      lastUpdateTime: "2026-01-27T01:12:47Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    observedGeneration: 3
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
kind: List
metadata:
  resourceVersion: ""
