apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"livekit","namespace":"livekit"},"spec":{"ports":[{"port":7880,"targetPort":7880}],"selector":{"app":"livekit-proxy"}}}
    creationTimestamp: "2026-01-25T20:32:30Z"
    name: livekit
    namespace: livekit
    resourceVersion: "10256"
    uid: e8525450-f152-4185-853a-c40c52ec85c0
  spec:
    clusterIP: 10.43.85.147
    clusterIPs:
    - 10.43.85.147
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 7880
      protocol: TCP
      targetPort: 7880
    selector:
      app: livekit-proxy
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"livekit-external","namespace":"livekit"},"spec":{"ports":[{"name":"http","nodePort":30780,"port":7880,"targetPort":7880},{"name":"rtc-tcp","nodePort":30781,"port":7881,"targetPort":7881},{"name":"turn-udp","nodePort":30478,"port":3478,"protocol":"UDP","targetPort":3478}],"selector":{"app":"livekit"},"type":"NodePort"}}
    creationTimestamp: "2026-01-25T20:29:14Z"
    name: livekit-external
    namespace: livekit
    resourceVersion: "10257"
    uid: cc842e45-f532-4885-be8b-bad5b7fd78f6
  spec:
    clusterIP: 10.43.106.82
    clusterIPs:
    - 10.43.106.82
    externalTrafficPolicy: Cluster
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http
      nodePort: 30780
      port: 7880
      protocol: TCP
      targetPort: 7880
    - name: rtc-tcp
      nodePort: 30781
      port: 7881
      protocol: TCP
      targetPort: 7881
    - name: turn-udp
      nodePort: 30478
      port: 3478
      protocol: UDP
      targetPort: 3478
    selector:
      app: livekit
    sessionAffinity: None
    type: NodePort
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"livekit-jwt","namespace":"livekit"},"spec":{"ports":[{"port":8080,"targetPort":8080}],"selector":{"app":"livekit-jwt"}}}
    creationTimestamp: "2026-01-25T20:22:12Z"
    name: livekit-jwt
    namespace: livekit
    resourceVersion: "10258"
    uid: c6e8a15c-0cb7-4b6b-a4e1-f0e7df4ee7ad
  spec:
    clusterIP: 10.43.4.73
    clusterIPs:
    - 10.43.4.73
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: livekit-jwt
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"livekit-proxy","namespace":"livekit"},"spec":{"ports":[{"port":7880,"targetPort":7880}],"selector":{"app":"livekit-proxy"}}}
    creationTimestamp: "2026-01-25T20:32:18Z"
    name: livekit-proxy
    namespace: livekit
    resourceVersion: "10259"
    uid: 56745c67-e7ca-4731-9bfa-ec80fe952bc9
  spec:
    clusterIP: 10.43.135.117
    clusterIPs:
    - 10.43.135.117
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 7880
      protocol: TCP
      targetPort: 7880
    selector:
      app: livekit-proxy
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"livekit-server","namespace":"livekit"},"spec":{"ports":[{"name":"http","port":7880,"targetPort":7880},{"name":"rtc-tcp","port":7881,"targetPort":7881}],"selector":{"app":"livekit"}}}
    creationTimestamp: "2026-01-25T20:32:29Z"
    name: livekit-server
    namespace: livekit
    resourceVersion: "10260"
    uid: 359235a1-be92-4d69-9854-c87400ce0390
  spec:
    clusterIP: 10.43.86.3
    clusterIPs:
    - 10.43.86.3
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http
      port: 7880
      protocol: TCP
      targetPort: 7880
    - name: rtc-tcp
      port: 7881
      protocol: TCP
      targetPort: 7881
    selector:
      app: livekit
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
