apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"tekton-dashboard","app.kubernetes.io/component":"dashboard","app.kubernetes.io/instance":"default","app.kubernetes.io/name":"dashboard","app.kubernetes.io/part-of":"tekton-dashboard","app.kubernetes.io/version":"v0.63.1","dashboard.tekton.dev/release":"v0.63.1","version":"v0.63.1"},"name":"tekton-dashboard","namespace":"tekton-pipelines"},"spec":{"ports":[{"name":"http","port":9097,"protocol":"TCP","targetPort":9097}],"selector":{"app.kubernetes.io/component":"dashboard","app.kubernetes.io/instance":"default","app.kubernetes.io/name":"dashboard","app.kubernetes.io/part-of":"tekton-dashboard"}}}
    creationTimestamp: "2026-01-18T15:16:16Z"
    labels:
      app: tekton-dashboard
      app.kubernetes.io/component: dashboard
      app.kubernetes.io/instance: default
      app.kubernetes.io/name: dashboard
      app.kubernetes.io/part-of: tekton-dashboard
      app.kubernetes.io/version: v0.63.1
      dashboard.tekton.dev/release: v0.63.1
      version: v0.63.1
    name: tekton-dashboard
    namespace: tekton-pipelines
    resourceVersion: "10295"
    uid: caa75cb2-df8d-4df6-b96e-9b4013b907db
  spec:
    clusterIP: 10.43.62.3
    clusterIPs:
    - 10.43.62.3
    externalTrafficPolicy: Cluster
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http
      nodePort: 30097
      port: 9097
      protocol: TCP
      targetPort: 9097
    selector:
      app.kubernetes.io/component: dashboard
      app.kubernetes.io/instance: default
      app.kubernetes.io/name: dashboard
      app.kubernetes.io/part-of: tekton-dashboard
    sessionAffinity: None
    type: NodePort
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      meta.helm.sh/release-name: tekton
      meta.helm.sh/release-namespace: tekton-pipelines
    creationTimestamp: "2026-01-18T09:23:13Z"
    labels:
      app: tekton-events-controller
      app.kubernetes.io/component: events
      app.kubernetes.io/instance: default
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: events
      app.kubernetes.io/part-of: tekton-pipelines
      app.kubernetes.io/version: v1.6.0
      pipeline.tekton.dev/release: v1.6.0
      version: v1.6.0
    name: tekton-events-controller
    namespace: tekton-pipelines
    resourceVersion: "10296"
    uid: eb44ee51-fddd-400e-83ef-787e86f39c01
  spec:
    clusterIP: 10.43.246.211
    clusterIPs:
    - 10.43.246.211
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http-metrics
      port: 9090
      protocol: TCP
      targetPort: 9090
    - name: http-profiling
      port: 8008
      protocol: TCP
      targetPort: 8008
    - name: probes
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app.kubernetes.io/component: events
      app.kubernetes.io/instance: default
      app.kubernetes.io/name: events
      app.kubernetes.io/part-of: tekton-pipelines
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      meta.helm.sh/release-name: tekton
      meta.helm.sh/release-namespace: tekton-pipelines
    creationTimestamp: "2026-01-18T09:23:13Z"
    labels:
      app: tekton-pipelines-controller
      app.kubernetes.io/component: controller
      app.kubernetes.io/instance: default
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: controller
      app.kubernetes.io/part-of: tekton-pipelines
      app.kubernetes.io/version: v1.6.0
      pipeline.tekton.dev/release: v1.6.0
      version: v1.6.0
    name: tekton-pipelines-controller
    namespace: tekton-pipelines
    resourceVersion: "10297"
    uid: 9d5ed54e-f78a-41a2-a878-69162c1c8ce4
  spec:
    clusterIP: 10.43.214.134
    clusterIPs:
    - 10.43.214.134
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http-metrics
      port: 9090
      protocol: TCP
      targetPort: 9090
    - name: http-profiling
      port: 8008
      protocol: TCP
      targetPort: 8008
    - name: probes
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app.kubernetes.io/component: controller
      app.kubernetes.io/instance: default
      app.kubernetes.io/name: controller
      app.kubernetes.io/part-of: tekton-pipelines
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      meta.helm.sh/release-name: tekton
      meta.helm.sh/release-namespace: tekton-pipelines
    creationTimestamp: "2026-01-18T09:23:13Z"
    labels:
      app: tekton-pipelines-remote-resolvers
      app.kubernetes.io/component: resolvers
      app.kubernetes.io/instance: default
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: resolvers
      app.kubernetes.io/part-of: tekton-pipelines
      app.kubernetes.io/version: v1.6.0
      pipeline.tekton.dev/release: v1.6.0
      version: v1.6.0
    name: tekton-pipelines-remote-resolvers
    namespace: tekton-pipelines
    resourceVersion: "10298"
    uid: aeed742d-2f30-40d1-8186-9e8314f2ea24
  spec:
    clusterIP: 10.43.103.31
    clusterIPs:
    - 10.43.103.31
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http-metrics
      port: 9090
      protocol: TCP
      targetPort: 9090
    - name: http-profiling
      port: 8008
      protocol: TCP
      targetPort: 8008
    - name: probes
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app.kubernetes.io/component: resolvers
      app.kubernetes.io/instance: default
      app.kubernetes.io/name: resolvers
      app.kubernetes.io/part-of: tekton-pipelines
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      meta.helm.sh/release-name: tekton
      meta.helm.sh/release-namespace: tekton-pipelines
    creationTimestamp: "2026-01-18T09:23:13Z"
    labels:
      app: tekton-pipelines-webhook
      app.kubernetes.io/component: webhook
      app.kubernetes.io/instance: default
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: webhook
      app.kubernetes.io/part-of: tekton-pipelines
      app.kubernetes.io/version: v1.6.0
      pipeline.tekton.dev/release: v1.6.0
      version: v1.6.0
    name: tekton-pipelines-webhook
    namespace: tekton-pipelines
    resourceVersion: "10299"
    uid: 111245f2-6684-482d-848c-bbce2360e670
  spec:
    clusterIP: 10.43.5.213
    clusterIPs:
    - 10.43.5.213
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http-metrics
      port: 9090
      protocol: TCP
      targetPort: metrics
    - name: http-profiling
      port: 8008
      protocol: TCP
      targetPort: profiling
    - name: https-webhook
      port: 443
      protocol: TCP
      targetPort: https-webhook
    - name: probes
      port: 8080
      protocol: TCP
      targetPort: probes
    selector:
      app.kubernetes.io/component: webhook
      app.kubernetes.io/instance: default
      app.kubernetes.io/name: webhook
      app.kubernetes.io/part-of: tekton-pipelines
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
