apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      argocd.argoproj.io/tracking-id: kubeview:apps/Deployment:kubeview/kubeview
      deployment.kubernetes.io/revision: "26"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"kubeview:apps/Deployment:kubeview/kubeview"},"labels":{"app.kubernetes.io/instance":"kubeview","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"kubeview","app.kubernetes.io/version":"2.1.1","helm.sh/chart":"kubeview-2.0.6"},"name":"kubeview","namespace":"kubeview"},"spec":{"replicas":1,"selector":{"matchLabels":{"app.kubernetes.io/instance":"kubeview","app.kubernetes.io/name":"kubeview"}},"template":{"metadata":{"labels":{"app.kubernetes.io/instance":"kubeview","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"kubeview","app.kubernetes.io/version":"2.1.1","helm.sh/chart":"kubeview-2.0.6"}},"spec":{"containers":[{"env":null,"image":"ghcr.io/benc-uk/kubeview:latest","imagePullPolicy":"Always","livenessProbe":{"httpGet":{"path":"/health","port":8000}},"name":"kubeview","ports":[{"containerPort":8000,"name":"http","protocol":"TCP"}],"readinessProbe":{"httpGet":{"path":"/health","port":8000}},"resources":{"limits":{"cpu":"100m","memory":"128Mi"},"requests":{"cpu":"50m","memory":"64Mi"}}}],"serviceAccountName":"kubeview"}}}}
    creationTimestamp: "2026-01-20T02:13:47Z"
    generation: 26
    labels:
      app.kubernetes.io/instance: kubeview
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: kubeview
      app.kubernetes.io/version: 2.1.1
      helm.sh/chart: kubeview-2.0.6
    name: kubeview
    namespace: kubeview
    resourceVersion: "1013"
    uid: 0eb1e31e-0195-492a-8fe2-0e54c782a975
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app.kubernetes.io/instance: kubeview
        app.kubernetes.io/name: kubeview
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        annotations:
          kubectl.kubernetes.io/restartedAt: "2026-01-26T08:05:06Z"
        labels:
          app.kubernetes.io/instance: kubeview
          app.kubernetes.io/managed-by: Helm
          app.kubernetes.io/name: kubeview
          app.kubernetes.io/version: 2.1.1
          helm.sh/chart: kubeview-2.0.6
      spec:
        containers:
        - image: ghcr.io/benc-uk/kubeview:latest
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8000
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: kubeview
          ports:
          - containerPort: 8000
            name: http
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8000
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccount: kubeview
        serviceAccountName: kubeview
        terminationGracePeriodSeconds: 30
  status:
    conditions:
    - lastTransitionTime: "2026-01-26T08:05:06Z"
      lastUpdateTime: "2026-01-26T08:05:42Z"
      message: ReplicaSet "kubeview-56bdcdc764" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    - lastTransitionTime: "2026-01-27T01:12:16Z"
      lastUpdateTime: "2026-01-27T01:12:16Z"
      message: Deployment does not have minimum availability.
      reason: MinimumReplicasUnavailable
      status: "False"
      type: Available
    observedGeneration: 26
    replicas: 1
    unavailableReplicas: 1
    updatedReplicas: 1
kind: List
metadata:
  resourceVersion: ""
