apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "holm-mind.fullname" . }}-html
  labels:
    {{- include "holm-mind.labels" . | nindent 4 }}
data:
  index.html: |
{{ .Files.Get "files/index.html" | indent 4 }}
