apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "holm-mind.fullname" . }}-server
  labels:
    {{- include "holm-mind.labels" . | nindent 4 }}
data:
  server.js: |
{{ .Files.Get "files/server.js" | indent 4 }}
