{{- if .Values.httpRoute.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "holm-mind.fullname" . }}
  labels:
    {{- include "holm-mind.labels" . | nindent 4 }}
spec:
  hostnames:
  - {{ .Values.httpRoute.hostname }}
  parentRefs:
  - name: {{ .Values.httpRoute.gateway.name }}
    namespace: {{ .Values.httpRoute.gateway.namespace }}
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: {{ .Values.httpRoute.path }}
    backendRefs:
    - name: {{ include "holm-mind.fullname" . }}
      port: {{ .Values.service.port }}
{{- end }}
