apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.auth.secretName }}
  labels:
    {{- include "holm-mind.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.auth.secretKey }}: {{ .Values.auth.password | quote }}
