{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "holm-mind.serviceAccountName" . }}
  labels:
    {{- include "holm-mind.labels" . | nindent 4 }}
{{- end }}
