apiVersion: v1
items:
- apiVersion: v1
  data:
    ca.crt: |
      -----BEGIN CERTIFICATE-----
      MIIBdjCCAR2gAwIBAgIBADAKBggqhkjOPQQDAjAjMSEwHwYDVQQDDBhrM3Mtc2Vy
      dmVyLWNhQDE3Njg0ODg1OTUwHhcNMjYwMTE1MTQ0OTU1WhcNMzYwMTEzMTQ0OTU1
      WjAjMSEwHwYDVQQDDBhrM3Mtc2VydmVyLWNhQDE3Njg0ODg1OTUwWTATBgcqhkjO
      PQIBBggqhkjOPQMBBwNCAAS5M3qca7X6I+z9JEP6m2z24D0Vxp/N9riBEnGH45Cd
      2BskCdidQJnMjVhm+Cb/XskOINIf6xwmtSvUe0yvjF1eo0IwQDAOBgNVHQ8BAf8E
      BAMCAqQwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUirW/RlF+LEjL/PJV27md
      5o8hlsUwCgYIKoZIzj0EAwIDRwAwRAIgWFi90tm3iGOxztyDXsQS5Xmt3KWl3hX5
      GVkFVp7VWrYCIH350uTqoqKYVuEL3AXTToIVryQVnEEUCxKpDRVjLsm9
      -----END CERTIFICATE-----
  kind: ConfigMap
  metadata:
    annotations:
      kubernetes.io/description: Contains a CA bundle that can be used to verify the
        kube-apiserver when using internal endpoints such as the internal service
        IP or kubernetes.default.svc. No other usage is guaranteed across distributions
        of Kubernetes clusters.
    creationTimestamp: "2026-01-20T09:14:20Z"
    name: kube-root-ca.crt
    namespace: pihole
    resourceVersion: "810"
    uid: d6ffac09-0116-460a-bf26-3774c3bea0e3
- apiVersion: v1
  data:
    02-custom.conf: |
      addn-hosts=/etc/addn-hosts
    05-pihole-custom-cname.conf: ""
    addn-hosts: ""
  kind: ConfigMap
  metadata:
    annotations:
      argocd.argoproj.io/tracking-id: pihole:/ConfigMap:pihole/pihole-custom-dnsmasq
    creationTimestamp: "2026-01-20T09:14:25Z"
    labels:
      app: pihole
      chart: pihole-2.35.0
      heritage: Helm
      release: pihole
    name: pihole-custom-dnsmasq
    namespace: pihole
    resourceVersion: "811"
    uid: 97c2e78b-bcda-4069-991b-8c5ed488e8ef
kind: List
metadata:
  resourceVersion: ""
