apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"database","namespace":"immich"},"spec":{"externalName":"immich-postgres.immich.svc.cluster.local","ports":[{"port":5432,"protocol":"TCP","targetPort":5432}],"type":"ExternalName"}}
    creationTimestamp: "2026-01-19T05:26:52Z"
    name: database
    namespace: immich
    resourceVersion: "10234"
    uid: f9594121-b359-4046-a019-83dea032efd8
  spec:
    externalName: immich-postgres.immich.svc.cluster.local
    ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
    sessionAffinity: None
    type: ExternalName
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      gethomepage.dev/description: Photo Management (Local)
      gethomepage.dev/enabled: "true"
      gethomepage.dev/group: Local Apps
      gethomepage.dev/href: http://192.168.8.197:30283
      gethomepage.dev/icon: immich.svg
      gethomepage.dev/name: Immich
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"gethomepage.dev/description":"Photo Management (Local)","gethomepage.dev/enabled":"true","gethomepage.dev/group":"Local Apps","gethomepage.dev/href":"http://192.168.8.197:30283","gethomepage.dev/icon":"immich.svg","gethomepage.dev/name":"Immich"},"name":"immich-external","namespace":"immich"},"spec":{"ports":[{"nodePort":30283,"port":2283,"protocol":"TCP","targetPort":2283}],"selector":{"app.kubernetes.io/instance":"immich","app.kubernetes.io/name":"server"},"type":"NodePort"}}
    creationTimestamp: "2026-01-19T05:29:10Z"
    name: immich-external
    namespace: immich
    resourceVersion: "10235"
    uid: 6c21f70c-8125-4969-8574-37b3302c6e0f
  spec:
    clusterIP: 10.43.118.194
    clusterIPs:
    - 10.43.118.194
    externalTrafficPolicy: Cluster
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - nodePort: 30283
      port: 2283
      protocol: TCP
      targetPort: 2283
    selector:
      app.kubernetes.io/instance: immich
      app.kubernetes.io/name: server
    sessionAffinity: None
    type: NodePort
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      argocd.argoproj.io/tracking-id: immich:/Service:immich/immich-machine-learning
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"immich:/Service:immich/immich-machine-learning"},"labels":{"app.kubernetes.io/instance":"immich","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"machine-learning","app.kubernetes.io/service":"immich-machine-learning","app.kubernetes.io/version":"v2.0.0","helm.sh/chart":"immich-0.10.3"},"name":"immich-machine-learning","namespace":"immich"},"spec":{"ports":[{"name":"http","port":3003,"protocol":"TCP","targetPort":"http"}],"selector":{"app.kubernetes.io/controller":"main","app.kubernetes.io/instance":"immich","app.kubernetes.io/name":"machine-learning"},"type":"ClusterIP"}}
    creationTimestamp: "2026-01-19T05:06:53Z"
    labels:
      app.kubernetes.io/instance: immich
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: machine-learning
      app.kubernetes.io/service: immich-machine-learning
      app.kubernetes.io/version: v2.0.0
      helm.sh/chart: immich-0.10.3
    name: immich-machine-learning
    namespace: immich
    resourceVersion: "10236"
    uid: 863a0c3a-9cf5-4815-a654-80de4b9cdd66
  spec:
    clusterIP: 10.43.39.41
    clusterIPs:
    - 10.43.39.41
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http
      port: 3003
      protocol: TCP
      targetPort: http
    selector:
      app.kubernetes.io/controller: main
      app.kubernetes.io/instance: immich
      app.kubernetes.io/name: machine-learning
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"immich-postgres","namespace":"immich"},"spec":{"ports":[{"port":5432,"targetPort":5432}],"selector":{"app":"immich-postgres"}}}
    creationTimestamp: "2026-01-19T05:06:35Z"
    name: immich-postgres
    namespace: immich
    resourceVersion: "10237"
    uid: 5972cb80-9bfa-47d5-bfbf-ee0ab4386c5e
  spec:
    clusterIP: 10.43.85.57
    clusterIPs:
    - 10.43.85.57
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
    selector:
      app: immich-postgres
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"immich-redis-master","namespace":"immich"},"spec":{"ports":[{"port":6379,"targetPort":6379}],"selector":{"app":"immich-redis"}}}
    creationTimestamp: "2026-01-19T05:06:57Z"
    name: immich-redis-master
    namespace: immich
    resourceVersion: "10238"
    uid: d78037a1-5cec-4cd2-a2f5-0ee826d5ef55
  spec:
    clusterIP: 10.43.186.15
    clusterIPs:
    - 10.43.186.15
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 6379
      protocol: TCP
      targetPort: 6379
    selector:
      app: immich-redis
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      argocd.argoproj.io/tracking-id: immich:/Service:immich/immich-server
      gethomepage.dev/description: Photo Management
      gethomepage.dev/enabled: "true"
      gethomepage.dev/group: Applications
      gethomepage.dev/href: https://holm.chat/immich
      gethomepage.dev/icon: immich.svg
      gethomepage.dev/name: Immich
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"immich:/Service:immich/immich-server"},"labels":{"app.kubernetes.io/instance":"immich","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"server","app.kubernetes.io/service":"immich-server","app.kubernetes.io/version":"v2.0.0","helm.sh/chart":"immich-0.10.3"},"name":"immich-server","namespace":"immich"},"spec":{"ports":[{"name":"http","port":2283,"protocol":"TCP","targetPort":"http"}],"selector":{"app.kubernetes.io/controller":"main","app.kubernetes.io/instance":"immich","app.kubernetes.io/name":"server"},"type":"ClusterIP"}}
    creationTimestamp: "2026-01-19T05:06:53Z"
    labels:
      app.kubernetes.io/instance: immich
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: server
      app.kubernetes.io/service: immich-server
      app.kubernetes.io/version: v2.0.0
      helm.sh/chart: immich-0.10.3
    name: immich-server
    namespace: immich
    resourceVersion: "10239"
    uid: 49485995-3235-4f35-b130-2157c07f6224
  spec:
    clusterIP: 10.43.69.154
    clusterIPs:
    - 10.43.69.154
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http
      port: 2283
      protocol: TCP
      targetPort: http
    selector:
      app.kubernetes.io/controller: main
      app.kubernetes.io/instance: immich
      app.kubernetes.io/name: server
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"immich-valkey","namespace":"immich"},"spec":{"externalName":"immich-redis-master.immich.svc.cluster.local","ports":[{"port":6379,"protocol":"TCP","targetPort":6379}],"type":"ExternalName"}}
    creationTimestamp: "2026-01-19T05:25:50Z"
    name: immich-valkey
    namespace: immich
    resourceVersion: "10240"
    uid: b879ae19-d0b1-4de2-91d6-49431b3f74bc
  spec:
    externalName: immich-redis-master.immich.svc.cluster.local
    ports:
    - port: 6379
      protocol: TCP
      targetPort: 6379
    sessionAffinity: None
    type: ExternalName
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
