apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"storage","app.kubernetes.io/name":"collector","app.kubernetes.io/part-of":"ytarchive"},"name":"collector","namespace":"ytarchive"},"spec":{"ports":[{"name":"http","port":8081,"protocol":"TCP","targetPort":8081}],"selector":{"app.kubernetes.io/component":"storage","app.kubernetes.io/name":"collector"},"type":"ClusterIP"}}
    creationTimestamp: "2026-01-25T02:57:17Z"
    labels:
      app.kubernetes.io/component: storage
      app.kubernetes.io/name: collector
      app.kubernetes.io/part-of: ytarchive
    name: collector
    namespace: ytarchive
    resourceVersion: "10310"
    uid: 70863d90-6ba9-46c4-b040-2a40f4a35941
  spec:
    clusterIP: 10.43.248.111
    clusterIPs:
    - 10.43.248.111
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http
      port: 8081
      protocol: TCP
      targetPort: 8081
    selector:
      app.kubernetes.io/component: storage
      app.kubernetes.io/name: collector
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      argocd.argoproj.io/tracking-id: ytarchive:/Service:ytarchive/postgres
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"ytarchive:/Service:ytarchive/postgres"},"labels":{"app.kubernetes.io/component":"database","app.kubernetes.io/name":"postgres","app.kubernetes.io/part-of":"ytarchive"},"name":"postgres","namespace":"ytarchive"},"spec":{"ports":[{"name":"postgres","port":5432,"protocol":"TCP","targetPort":5432}],"selector":{"app.kubernetes.io/component":"database","app.kubernetes.io/name":"postgres","app.kubernetes.io/part-of":"ytarchive"},"type":"ClusterIP"}}
    creationTimestamp: "2026-01-25T02:57:19Z"
    labels:
      app.kubernetes.io/component: database
      app.kubernetes.io/name: postgres
      app.kubernetes.io/part-of: ytarchive
    name: postgres
    namespace: ytarchive
    resourceVersion: "10311"
    uid: 0047d56c-f24a-43ba-8cf0-2b60b8a668e2
  spec:
    clusterIP: 10.43.10.107
    clusterIPs:
    - 10.43.10.107
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
    selector:
      app.kubernetes.io/component: database
      app.kubernetes.io/name: postgres
      app.kubernetes.io/part-of: ytarchive
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      argocd.argoproj.io/tracking-id: ytarchive:/Service:ytarchive/redis
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"ytarchive:/Service:ytarchive/redis"},"labels":{"app.kubernetes.io/component":"queue","app.kubernetes.io/name":"redis","app.kubernetes.io/part-of":"ytarchive"},"name":"redis","namespace":"ytarchive"},"spec":{"ports":[{"name":"redis","port":6379,"protocol":"TCP","targetPort":"redis"}],"selector":{"app.kubernetes.io/component":"queue","app.kubernetes.io/name":"redis","app.kubernetes.io/part-of":"ytarchive"},"type":"ClusterIP"}}
    creationTimestamp: "2026-01-22T12:05:10Z"
    labels:
      app.kubernetes.io/component: queue
      app.kubernetes.io/name: redis
      app.kubernetes.io/part-of: ytarchive
    name: redis
    namespace: ytarchive
    resourceVersion: "10312"
    uid: e56c44aa-dfec-4825-a7a0-3aedacf10ef1
  spec:
    clusterIP: 10.43.254.97
    clusterIPs:
    - 10.43.254.97
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: redis
      port: 6379
      protocol: TCP
      targetPort: redis
    selector:
      app.kubernetes.io/component: queue
      app.kubernetes.io/name: redis
      app.kubernetes.io/part-of: ytarchive
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      argocd.argoproj.io/tracking-id: ytarchive:/Service:ytarchive/ytarchive-controller
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"ytarchive:/Service:ytarchive/ytarchive-controller"},"labels":{"app.kubernetes.io/component":"api","app.kubernetes.io/name":"controller","app.kubernetes.io/part-of":"ytarchive"},"name":"ytarchive-controller","namespace":"ytarchive"},"spec":{"ports":[{"name":"http","port":80,"protocol":"TCP","targetPort":"http"}],"selector":{"app.kubernetes.io/component":"api","app.kubernetes.io/name":"controller","app.kubernetes.io/part-of":"ytarchive"},"type":"ClusterIP"}}
    creationTimestamp: "2026-01-22T12:11:26Z"
    labels:
      app.kubernetes.io/component: api
      app.kubernetes.io/name: controller
      app.kubernetes.io/part-of: ytarchive
    name: ytarchive-controller
    namespace: ytarchive
    resourceVersion: "10313"
    uid: 51c5b52f-c70d-4d27-9758-8d41327cf8d3
  spec:
    clusterIP: 10.43.47.138
    clusterIPs:
    - 10.43.47.138
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
    selector:
      app.kubernetes.io/component: api
      app.kubernetes.io/name: controller
      app.kubernetes.io/part-of: ytarchive
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      argocd.argoproj.io/tracking-id: ytarchive:/Service:ytarchive/ytarchive-nodeport
      gethomepage.dev/description: YouTube Archiver
      gethomepage.dev/enabled: "true"
      gethomepage.dev/group: Local Apps
      gethomepage.dev/href: http://192.168.8.197:30580
      gethomepage.dev/icon: youtube.svg
      gethomepage.dev/name: YT Archive
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"ytarchive:/Service:ytarchive/ytarchive-nodeport","gethomepage.dev/description":"YouTube Archiver","gethomepage.dev/enabled":"true","gethomepage.dev/group":"Local Apps","gethomepage.dev/href":"http://192.168.8.197:30580","gethomepage.dev/icon":"youtube.svg","gethomepage.dev/name":"YT Archive"},"labels":{"app.kubernetes.io/component":"api","app.kubernetes.io/name":"controller","app.kubernetes.io/part-of":"ytarchive"},"name":"ytarchive-nodeport","namespace":"ytarchive"},"spec":{"ports":[{"name":"http","nodePort":30580,"port":80,"protocol":"TCP","targetPort":"http"}],"selector":{"app.kubernetes.io/component":"api","app.kubernetes.io/name":"controller","app.kubernetes.io/part-of":"ytarchive"},"type":"NodePort"}}
    creationTimestamp: "2026-01-24T23:33:30Z"
    labels:
      app.kubernetes.io/component: api
      app.kubernetes.io/name: controller
      app.kubernetes.io/part-of: ytarchive
    name: ytarchive-nodeport
    namespace: ytarchive
    resourceVersion: "10314"
    uid: 5f3fe1e4-aa2d-4f21-bf90-cea32cf1fc39
  spec:
    clusterIP: 10.43.160.54
    clusterIPs:
    - 10.43.160.54
    externalTrafficPolicy: Cluster
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http
      nodePort: 30580
      port: 80
      protocol: TCP
      targetPort: http
    selector:
      app.kubernetes.io/component: api
      app.kubernetes.io/name: controller
      app.kubernetes.io/part-of: ytarchive
    sessionAffinity: None
    type: NodePort
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
