apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"element-ui","namespace":"signal-web"},"spec":{"externalTrafficPolicy":"Cluster","internalTrafficPolicy":"Cluster","ipFamilies":["IPv4"],"ipFamilyPolicy":"SingleStack","ports":[{"port":80,"protocol":"TCP","targetPort":80}],"selector":{"app":"element-web"},"sessionAffinity":"None","type":"NodePort"},"status":{"loadBalancer":{}}}
    creationTimestamp: "2026-01-27T03:15:40Z"
    name: element-ui
    namespace: signal-web
    resourceVersion: "10291"
    uid: 8eb61511-a778-4ec3-90cd-af240a623f1f
  spec:
    clusterIP: 10.43.108.100
    clusterIPs:
    - 10.43.108.100
    externalTrafficPolicy: Cluster
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - nodePort: 30369
      port: 80
      protocol: TCP
      targetPort: 80
    selector:
      app: element-web
    sessionAffinity: None
    type: NodePort
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"postgres","namespace":"signal-web"},"spec":{"ports":[{"port":5432}],"selector":{"app":"postgres"}}}
    creationTimestamp: "2026-01-25T16:03:52Z"
    name: postgres
    namespace: signal-web
    resourceVersion: "10292"
    uid: de8de03b-0574-4837-8311-b7d7cdc2d8dd
  spec:
    clusterIP: 10.43.200.213
    clusterIPs:
    - 10.43.200.213
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
    selector:
      app: postgres
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"synapse","namespace":"signal-web"},"spec":{"ports":[{"port":8008,"targetPort":8008}],"selector":{"app":"synapse"}}}
    creationTimestamp: "2026-01-25T16:03:53Z"
    name: synapse
    namespace: signal-web
    resourceVersion: "10293"
    uid: 3af552eb-7932-4ac7-9137-4f3df2cdd450
  spec:
    clusterIP: 10.43.80.85
    clusterIPs:
    - 10.43.80.85
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 8008
      protocol: TCP
      targetPort: 8008
    selector:
      app: synapse
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"synapse-nodeport","namespace":"signal-web"},"spec":{"ports":[{"nodePort":30388,"port":8008,"targetPort":8008}],"selector":{"app":"synapse"},"type":"NodePort"}}
    creationTimestamp: "2026-01-25T16:03:54Z"
    name: synapse-nodeport
    namespace: signal-web
    resourceVersion: "10294"
    uid: ee41d6fd-c1e4-486d-8d32-4d5a8f96a69a
  spec:
    clusterIP: 10.43.130.225
    clusterIPs:
    - 10.43.130.225
    externalTrafficPolicy: Cluster
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - nodePort: 30388
      port: 8008
      protocol: TCP
      targetPort: 8008
    selector:
      app: synapse
    sessionAffinity: None
    type: NodePort
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
