apiVersion: v1
kind: Service
metadata:
  name: ytarchive-nodeport
  namespace: ytarchive
  labels:
    app.kubernetes.io/name: controller
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: ytarchive
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "YT Archive"
    gethomepage.dev/description: "YouTube Archiver"
    gethomepage.dev/group: "Local Apps"
    gethomepage.dev/icon: "youtube.svg"
    gethomepage.dev/href: "http://192.168.8.197:30580"
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: controller
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: ytarchive
  ports:
    - name: http
      port: 80
      targetPort: http
      nodePort: 30580
      protocol: TCP
