apiVersion: v1
kind: Service
metadata:
  name: ytarchive-controller
  namespace: ytarchive
  labels:
    app.kubernetes.io/name: controller
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: ytarchive
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: controller
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: ytarchive
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
