apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ytarchive
  namespace: ytarchive
spec:
  hostnames:
    - holm.chat
  parentRefs:
    - name: main-gateway
      namespace: envoy-gateway-system
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /ytarchive
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /
      backendRefs:
        - name: ytarchive-controller
          port: 80
