apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ytarchive-data
  namespace: ytarchive
  labels:
    app.kubernetes.io/name: storage
    app.kubernetes.io/component: data
    app.kubernetes.io/part-of: ytarchive
spec:
  storageClassName: qnap-iscsi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
