apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"element-web","namespace":"matrix"},"spec":{"ports":[{"port":80,"targetPort":80}],"selector":{"app":"element-web"}}}
    creationTimestamp: "2026-01-25T00:46:53Z"
    name: element-web
    namespace: matrix
    resourceVersion: "10261"
    uid: 128d42d6-1a17-4203-b8c3-d737ca6c8953
  spec:
    clusterIP: 10.43.45.106
    clusterIPs:
    - 10.43.45.106
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 80
      protocol: TCP
      targetPort: 80
    selector:
      app: element-web
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"mas","namespace":"matrix"},"spec":{"ports":[{"name":"http","port":8080,"targetPort":8080},{"name":"internal","port":8081,"targetPort":8081}],"selector":{"app":"mas"}}}
    creationTimestamp: "2026-01-25T02:45:43Z"
    name: mas
    namespace: matrix
    resourceVersion: "10262"
    uid: b0382d62-da86-4db7-ab0f-40176e1a7eba
  spec:
    clusterIP: 10.43.233.148
    clusterIPs:
    - 10.43.233.148
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: internal
      port: 8081
      protocol: TCP
      targetPort: 8081
    selector:
      app: mas
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"matrix-postgres","namespace":"matrix"},"spec":{"ports":[{"port":5432,"targetPort":5432}],"selector":{"app":"matrix-postgres"}}}
    creationTimestamp: "2026-01-25T00:34:33Z"
    name: matrix-postgres
    namespace: matrix
    resourceVersion: "10263"
    uid: b12a002e-6891-4ed9-865e-d02b4bcf10d0
  spec:
    clusterIP: 10.43.206.235
    clusterIPs:
    - 10.43.206.235
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
    selector:
      app: matrix-postgres
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"matrix-wellknown","namespace":"matrix"},"spec":{"ports":[{"port":80,"targetPort":80}],"selector":{"app":"matrix-wellknown"}}}
    creationTimestamp: "2026-01-25T00:42:58Z"
    name: matrix-wellknown
    namespace: matrix
    resourceVersion: "10264"
    uid: 543fc916-074e-421c-b462-bf456214b396
  spec:
    clusterIP: 10.43.89.93
    clusterIPs:
    - 10.43.89.93
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 80
      protocol: TCP
      targetPort: 80
    selector:
      app: matrix-wellknown
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"synapse","namespace":"matrix"},"spec":{"ports":[{"name":"http","port":8008,"targetPort":8008}],"selector":{"app":"synapse"}}}
    creationTimestamp: "2026-01-25T00:37:04Z"
    name: synapse
    namespace: matrix
    resourceVersion: "10265"
    uid: d7a5768f-bcde-4b06-aa13-1f33a106ecc7
  spec:
    clusterIP: 10.43.184.73
    clusterIPs:
    - 10.43.184.73
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http
      port: 8008
      protocol: TCP
      targetPort: 8008
    selector:
      app: synapse
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"synapse-admin","namespace":"matrix"},"spec":{"ports":[{"port":80,"targetPort":80}],"selector":{"app":"synapse-admin"}}}
    creationTimestamp: "2026-01-25T15:33:49Z"
    name: synapse-admin
    namespace: matrix
    resourceVersion: "10266"
    uid: 83a75743-c2c9-4184-acf5-4abc7e8f9ea4
  spec:
    clusterIP: 10.43.233.166
    clusterIPs:
    - 10.43.233.166
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 80
      protocol: TCP
      targetPort: 80
    selector:
      app: synapse-admin
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
