apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"elasticsearch","namespace":"tubearchivist"},"spec":{"ports":[{"port":9200,"targetPort":9200}],"selector":{"app":"elasticsearch"}}}
    creationTimestamp: "2026-01-25T06:58:18Z"
    name: elasticsearch
    namespace: tubearchivist
    resourceVersion: "10304"
    uid: 4bc2849e-b581-44eb-ad23-fb2c1758d70a
  spec:
    clusterIP: 10.43.169.235
    clusterIPs:
    - 10.43.169.235
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 9200
      protocol: TCP
      targetPort: 9200
    selector:
      app: elasticsearch
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"ta-redis","namespace":"tubearchivist"},"spec":{"ports":[{"port":6379,"targetPort":6379}],"selector":{"app":"redis"}}}
    creationTimestamp: "2026-01-25T07:28:10Z"
    name: ta-redis
    namespace: tubearchivist
    resourceVersion: "10305"
    uid: 20369702-f4e4-4fd8-9114-39b60210d08c
  spec:
    clusterIP: 10.43.26.40
    clusterIPs:
    - 10.43.26.40
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 6379
      protocol: TCP
      targetPort: 6379
    selector:
      app: redis
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"tubearchivist","namespace":"tubearchivist"},"spec":{"ports":[{"port":8000,"targetPort":8000}],"selector":{"app":"tubearchivist"}}}
    creationTimestamp: "2026-01-25T07:04:03Z"
    name: tubearchivist
    namespace: tubearchivist
    resourceVersion: "10306"
    uid: d5e56d20-cd04-4fdc-9081-3c6341e36f0b
  spec:
    clusterIP: 10.43.249.63
    clusterIPs:
    - 10.43.249.63
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000
    selector:
      app: tubearchivist
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"tubearchivist-nodeport","namespace":"tubearchivist"},"spec":{"ports":[{"nodePort":30850,"port":8000,"targetPort":8000}],"selector":{"app":"tubearchivist"},"type":"NodePort"}}
    creationTimestamp: "2026-01-25T07:04:03Z"
    name: tubearchivist-nodeport
    namespace: tubearchivist
    resourceVersion: "10307"
    uid: 76b79a36-e681-4b1e-af38-4ce9eb50749f
  spec:
    clusterIP: 10.43.33.97
    clusterIPs:
    - 10.43.33.97
    externalTrafficPolicy: Cluster
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - nodePort: 30850
      port: 8000
      protocol: TCP
      targetPort: 8000
    selector:
      app: tubearchivist
    sessionAffinity: None
    type: NodePort
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
