apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      argocd.argoproj.io/tracking-id: argo-workflows:apps/Deployment:argo/argo-workflows-server
      deployment.kubernetes.io/revision: "17"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"argo-workflows:apps/Deployment:argo/argo-workflows-server"},"labels":{"app":"server","app.kubernetes.io/component":"server","app.kubernetes.io/instance":"argo-workflows","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"argo-workflows-server","app.kubernetes.io/part-of":"argo-workflows","app.kubernetes.io/version":"v3.7.8","helm.sh/chart":"argo-workflows-0.47.1"},"name":"argo-workflows-server","namespace":"argo"},"spec":{"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app.kubernetes.io/instance":"argo-workflows","app.kubernetes.io/name":"argo-workflows-server"}},"template":{"metadata":{"annotations":{"checksum/cm":"8c66291dcc8e75d2edf2834272b3a4e5b5bae3141633dd0d6b3030acffef3f26"},"labels":{"app":"server","app.kubernetes.io/component":"server","app.kubernetes.io/instance":"argo-workflows","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"argo-workflows-server","app.kubernetes.io/part-of":"argo-workflows","app.kubernetes.io/version":"v3.7.8","helm.sh/chart":"argo-workflows-0.47.1"}},"spec":{"containers":[{"args":["server","--configmap=argo-workflows-workflow-controller-configmap","--namespaced","--auth-mode=sso","--auth-mode=sso","--secure=false","--loglevel","info","--gloglevel","0","--log-format","text"],"env":[{"name":"IN_CLUSTER","value":"true"},{"name":"ARGO_NAMESPACE","valueFrom":{"fieldRef":{"apiVersion":"v1","fieldPath":"metadata.namespace"}}},{"name":"ARGO_BASE_HREF","value":"/argo-workflows/"}],"image":"quay.io/argoproj/argocli:v3.7.8","imagePullPolicy":"Always","name":"argo-server","ports":[{"containerPort":2746,"name":"web"}],"readinessProbe":{"httpGet":{"path":"/","port":2746,"scheme":"HTTP"},"initialDelaySeconds":10,"periodSeconds":20},"resources":{},"securityContext":{"allowPrivilegeEscalation":false,"capabilities":{"drop":["ALL"]},"readOnlyRootFilesystem":false,"runAsNonRoot":true},"volumeMounts":[{"mountPath":"/tmp","name":"tmp"}]}],"nodeSelector":{"kubernetes.io/os":"linux"},"serviceAccountName":"argo-workflows-server","terminationGracePeriodSeconds":30,"volumes":[{"emptyDir":{},"name":"tmp"}]}}}}
    creationTimestamp: "2026-01-19T12:40:11Z"
    generation: 17
    labels:
      app: server
      app.kubernetes.io/component: server
      app.kubernetes.io/instance: argo-workflows
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: argo-workflows-server
      app.kubernetes.io/part-of: argo-workflows
      app.kubernetes.io/version: v3.7.8
      helm.sh/chart: argo-workflows-0.47.1
    name: argo-workflows-server
    namespace: argo
    resourceVersion: "908"
    uid: dcab917a-c005-4877-8900-47654cbbd88e
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app.kubernetes.io/instance: argo-workflows
        app.kubernetes.io/name: argo-workflows-server
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        annotations:
          checksum/cm: 8c66291dcc8e75d2edf2834272b3a4e5b5bae3141633dd0d6b3030acffef3f26
          kubectl.kubernetes.io/restartedAt: "2026-01-19T20:09:47-08:00"
        labels:
          app: server
          app.kubernetes.io/component: server
          app.kubernetes.io/instance: argo-workflows
          app.kubernetes.io/managed-by: Helm
          app.kubernetes.io/name: argo-workflows-server
          app.kubernetes.io/part-of: argo-workflows
          app.kubernetes.io/version: v3.7.8
          helm.sh/chart: argo-workflows-0.47.1
      spec:
        containers:
        - args:
          - server
          - --configmap=argo-workflows-workflow-controller-configmap
          - --namespaced
          - --auth-mode=sso
          - --auth-mode=sso
          - --secure=false
          - --loglevel
          - info
          - --gloglevel
          - "0"
          - --log-format
          - text
          env:
          - name: IN_CLUSTER
            value: "true"
          - name: ARGO_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          - name: ARGO_BASE_HREF
            value: /argo-workflows/
          image: quay.io/argoproj/argocli:v3.7.8
          imagePullPolicy: Always
          name: argo-server
          ports:
          - containerPort: 2746
            name: web
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 2746
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 1
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: false
            runAsNonRoot: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /tmp
            name: tmp
        dnsPolicy: ClusterFirst
        nodeSelector:
          kubernetes.io/os: linux
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccount: argo-workflows-server
        serviceAccountName: argo-workflows-server
        terminationGracePeriodSeconds: 30
        volumes:
        - emptyDir: {}
          name: tmp
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2026-01-20T00:12:19Z"
      lastUpdateTime: "2026-01-21T11:56:04Z"
      message: ReplicaSet "argo-workflows-server-7b98689495" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    - lastTransitionTime: "2026-01-27T03:00:08Z"
      lastUpdateTime: "2026-01-27T03:00:08Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    observedGeneration: 17
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      argocd.argoproj.io/tracking-id: argo-workflows:apps/Deployment:argo/argo-workflows-workflow-controller
      deployment.kubernetes.io/revision: "2"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"argo-workflows:apps/Deployment:argo/argo-workflows-workflow-controller"},"labels":{"app":"workflow-controller","app.kubernetes.io/component":"workflow-controller","app.kubernetes.io/instance":"argo-workflows","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"argo-workflows-workflow-controller","app.kubernetes.io/part-of":"argo-workflows","app.kubernetes.io/version":"v3.7.8","helm.sh/chart":"argo-workflows-0.47.1"},"name":"argo-workflows-workflow-controller","namespace":"argo"},"spec":{"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app.kubernetes.io/instance":"argo-workflows","app.kubernetes.io/name":"argo-workflows-workflow-controller"}},"template":{"metadata":{"labels":{"app":"workflow-controller","app.kubernetes.io/component":"workflow-controller","app.kubernetes.io/instance":"argo-workflows","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"argo-workflows-workflow-controller","app.kubernetes.io/part-of":"argo-workflows","app.kubernetes.io/version":"v3.7.8","helm.sh/chart":"argo-workflows-0.47.1"}},"spec":{"containers":[{"args":["--configmap","argo-workflows-workflow-controller-configmap","--executor-image","quay.io/argoproj/argoexec:v3.7.8","--loglevel","info","--gloglevel","0","--log-format","text"],"command":["workflow-controller"],"env":[{"name":"ARGO_NAMESPACE","valueFrom":{"fieldRef":{"apiVersion":"v1","fieldPath":"metadata.namespace"}}},{"name":"LEADER_ELECTION_IDENTITY","valueFrom":{"fieldRef":{"apiVersion":"v1","fieldPath":"metadata.name"}}},{"name":"LEADER_ELECTION_DISABLE","value":"true"}],"image":"quay.io/argoproj/workflow-controller:v3.7.8","imagePullPolicy":"Always","livenessProbe":{"failureThreshold":3,"httpGet":{"path":"/healthz","port":6060},"initialDelaySeconds":90,"periodSeconds":60,"timeoutSeconds":30},"name":"controller","ports":[{"containerPort":9090,"name":"metrics"},{"containerPort":6060}],"resources":{},"securityContext":{"allowPrivilegeEscalation":false,"capabilities":{"drop":["ALL"]},"readOnlyRootFilesystem":true,"runAsNonRoot":true}}],"nodeSelector":{"kubernetes.io/os":"linux"},"serviceAccountName":"argo-workflows-workflow-controller"}}}}
    creationTimestamp: "2026-01-19T12:40:11Z"
    generation: 2
    labels:
      app: workflow-controller
      app.kubernetes.io/component: workflow-controller
      app.kubernetes.io/instance: argo-workflows
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: argo-workflows-workflow-controller
      app.kubernetes.io/part-of: argo-workflows
      app.kubernetes.io/version: v3.7.8
      helm.sh/chart: argo-workflows-0.47.1
    name: argo-workflows-workflow-controller
    namespace: argo
    resourceVersion: "909"
    uid: 8fedb697-32fd-4689-b96e-dcd33c199c24
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app.kubernetes.io/instance: argo-workflows
        app.kubernetes.io/name: argo-workflows-workflow-controller
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        labels:
          app: workflow-controller
          app.kubernetes.io/component: workflow-controller
          app.kubernetes.io/instance: argo-workflows
          app.kubernetes.io/managed-by: Helm
          app.kubernetes.io/name: argo-workflows-workflow-controller
          app.kubernetes.io/part-of: argo-workflows
          app.kubernetes.io/version: v3.7.8
          helm.sh/chart: argo-workflows-0.47.1
      spec:
        containers:
        - args:
          - --configmap
          - argo-workflows-workflow-controller-configmap
          - --executor-image
          - quay.io/argoproj/argoexec:v3.7.8
          - --loglevel
          - info
          - --gloglevel
          - "0"
          - --log-format
          - text
          command:
          - workflow-controller
          env:
          - name: ARGO_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          - name: LEADER_ELECTION_IDENTITY
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: LEADER_ELECTION_DISABLE
            value: "true"
          image: quay.io/argoproj/workflow-controller:v3.7.8
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 6060
              scheme: HTTP
            initialDelaySeconds: 90
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 30
          name: controller
          ports:
          - containerPort: 9090
            name: metrics
            protocol: TCP
          - containerPort: 6060
            protocol: TCP
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        nodeSelector:
          kubernetes.io/os: linux
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccount: argo-workflows-workflow-controller
        serviceAccountName: argo-workflows-workflow-controller
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2026-01-19T12:40:11Z"
      lastUpdateTime: "2026-01-21T11:55:36Z"
      message: ReplicaSet "argo-workflows-workflow-controller-74689ccbcf" has successfully
        progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    - lastTransitionTime: "2026-01-27T02:43:52Z"
      lastUpdateTime: "2026-01-27T02:43:52Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    observedGeneration: 2
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
kind: List
metadata:
  resourceVersion: ""
