apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      argocd.argoproj.io/tracking-id: argo-workflows:/Service:argo/argo-workflows-server
      gethomepage.dev/description: Workflow Engine
      gethomepage.dev/enabled: "true"
      gethomepage.dev/group: Infrastructure
      gethomepage.dev/href: https://holm.chat/argo-workflows
      gethomepage.dev/icon: argo.svg
      gethomepage.dev/name: Argo Workflows
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"argo-workflows:/Service:argo/argo-workflows-server"},"labels":{"app":"server","app.kubernetes.io/component":"server","app.kubernetes.io/instance":"argo-workflows","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"argo-workflows-server","app.kubernetes.io/part-of":"argo-workflows","app.kubernetes.io/version":"v3.7.8","helm.sh/chart":"argo-workflows-0.47.1"},"name":"argo-workflows-server","namespace":"argo"},"spec":{"ports":[{"port":2746,"targetPort":2746}],"selector":{"app.kubernetes.io/instance":"argo-workflows","app.kubernetes.io/name":"argo-workflows-server"},"sessionAffinity":"None","type":"ClusterIP"}}
    creationTimestamp: "2026-01-19T12:40:11Z"
    labels:
      app: server
      app.kubernetes.io/component: server
      app.kubernetes.io/instance: argo-workflows
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: argo-workflows-server
      app.kubernetes.io/part-of: argo-workflows
      app.kubernetes.io/version: v3.7.8
      helm.sh/chart: argo-workflows-0.47.1
    name: argo-workflows-server
    namespace: argo
    resourceVersion: "10138"
    uid: 7b6e9395-e026-442e-917b-60ee66536cfe
  spec:
    clusterIP: 10.43.196.106
    clusterIPs:
    - 10.43.196.106
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 2746
      protocol: TCP
      targetPort: 2746
    selector:
      app.kubernetes.io/instance: argo-workflows
      app.kubernetes.io/name: argo-workflows-server
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
