apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"minio","namespace":"velero"},"spec":{"ports":[{"name":"api","port":9000,"targetPort":9000},{"name":"console","port":9001,"targetPort":9001}],"selector":{"app":"minio"}}}
    creationTimestamp: "2026-01-27T00:15:24Z"
    name: minio
    namespace: velero
    resourceVersion: "10308"
    uid: e9d27c94-339f-4a00-ac8a-b0042502d803
  spec:
    clusterIP: 10.43.13.80
    clusterIPs:
    - 10.43.13.80
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: api
      port: 9000
      protocol: TCP
      targetPort: 9000
    - name: console
      port: 9001
      protocol: TCP
      targetPort: 9001
    selector:
      app: minio
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"velero-ui","namespace":"velero"},"spec":{"ports":[{"port":80,"targetPort":3000}],"selector":{"app":"velero-ui"}}}
    creationTimestamp: "2026-01-27T00:28:33Z"
    name: velero-ui
    namespace: velero
    resourceVersion: "10309"
    uid: 83889ad4-a770-4b7f-b401-2e6228d85606
  spec:
    clusterIP: 10.43.97.29
    clusterIPs:
    - 10.43.97.29
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
    selector:
      app: velero-ui
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
